// SPDX-License-Identifier: MIT
// Copyright (c) 2026 Pradeep Mouli

/**
 * Builds dist/tokens.css and dist/tokens.js from src/tokens.json.
 *
 * Emits two outputs:
 *  - dist/tokens.css — `:root { --foo: ... }` plus a `[data-theme="dark"]`
 *    block that overrides only `--color-*` variables.
 *  - dist/tokens.js  — typed `as const` object for React consumers that
 *    need raw values (rare; primitives should consume CSS variables).
 *
 * CSS-variable naming is locked: changes to the namespace tree in
 * `tokens.json` ripple through every consumer (landing site, docs theme,
 * Studio's Tailwind config). The snapshot test in
 * `packages/design-tokens/tests/build.test.ts` enforces stability.
 */

import { readFile, writeFile, mkdir } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, '..');
const OUT = resolve(ROOT, 'dist');

type Tokens = Record<string, unknown>;

/** Flatten a nested object into kebab-cased paths -> string values. */
function flatten(obj: Tokens, prefix = ''): Array<[string, string]> {
  const out: Array<[string, string]> = [];
  for (const [rawKey, val] of Object.entries(obj)) {
    if (rawKey.startsWith('_') || rawKey.startsWith('$')) continue;
    const key = rawKey.replace(/_/g, '-');
    const path = prefix ? `${prefix}-${key}` : key;
    if (val !== null && typeof val === 'object' && !Array.isArray(val)) {
      out.push(...flatten(val as Tokens, path));
    } else if (typeof val === 'string') {
      out.push([path, val]);
    } else if (typeof val === 'number') {
      out.push([path, String(val)]);
    }
  }
  return out;
}

function emitCss(tokens: Tokens): string {
  const light = flatten(
    Object.fromEntries(
      Object.entries(tokens).filter(([k]) => k !== 'color_dark' && k !== 'version')
    )
  );
  const dark = flatten({ color: (tokens['color_dark'] as Tokens) ?? {} });
  const lightLines = light.map(([k, v]) => `  --${k}: ${v};`).join('\n');
  const darkLines = dark.map(([k, v]) => `  --${k}: ${v};`).join('\n');
  return [
    '/* Generated by @rune-langium/design-tokens build.ts. Do not edit. */',
    ':root {',
    lightLines,
    '}',
    '',
    '[data-theme="dark"] {',
    darkLines,
    '}',
    ''
  ].join('\n');
}

function emitTs(tokens: Tokens): string {
  return [
    '// Generated by @rune-langium/design-tokens build.ts. Do not edit.',
    `export const tokens = ${JSON.stringify(tokens, null, 2)} as const;`,
    'export type Tokens = typeof tokens;',
    ''
  ].join('\n');
}

/**
 * Walk the JSON and emit a fully-typed `.d.ts` so consumers get
 * compile-time errors on misspelled token paths (e.g.
 * `tokens.color.surface[1]` typo'd as `tokens.colour.surface[1]`).
 *
 * The runtime values stay `string | number` rather than narrow string
 * literals — narrowing every value would more than double the file size
 * and consumers don't typically branch on token contents.
 */
function emitDts(tokens: Tokens): string {
  const lines: string[] = [
    '// Generated by @rune-langium/design-tokens build.ts. Do not edit.',
    'export interface Tokens ' + emitDtsShape(tokens, 0),
    'export declare const tokens: Tokens;',
    ''
  ];
  return lines.join('\n');
}

function emitDtsShape(value: unknown, depth: number): string {
  if (typeof value === 'string') return 'string';
  if (typeof value === 'number') return 'number';
  if (typeof value === 'boolean') return 'boolean';
  if (Array.isArray(value)) return `${valueLeafType(value[0])}[]`;
  if (value === null || typeof value !== 'object') return 'unknown';

  const indent = '  '.repeat(depth);
  const inner = '  '.repeat(depth + 1);
  const entries = Object.entries(value as Record<string, unknown>).filter(
    ([k]) => !k.startsWith('_') && !k.startsWith('$')
  );
  if (entries.length === 0) return '{}';
  const body = entries
    .map(([k, v]) => {
      const safeKey = /^[a-zA-Z_$][a-zA-Z0-9_$]*$/.test(k) ? k : JSON.stringify(k);
      return `${inner}readonly ${safeKey}: ${emitDtsShape(v, depth + 1)};`;
    })
    .join('\n');
  return `{\n${body}\n${indent}}`;
}

function valueLeafType(v: unknown): string {
  if (typeof v === 'string') return 'string';
  if (typeof v === 'number') return 'number';
  if (typeof v === 'boolean') return 'boolean';
  return 'unknown';
}

async function main() {
  const raw = await readFile(resolve(ROOT, 'src/tokens.json'), 'utf8');
  const tokens = JSON.parse(raw) as Tokens;
  await mkdir(OUT, { recursive: true });
  await writeFile(resolve(OUT, 'tokens.css'), emitCss(tokens), 'utf8');
  await writeFile(resolve(OUT, 'tokens.js'), emitTs(tokens), 'utf8');
  // Strongly-typed .d.ts generated from the same JSON. Misspelled token
  // paths (e.g. `tokens.colour.surface[1]`) fail at compile time.
  await writeFile(resolve(OUT, 'tokens.d.ts'), emitDts(tokens), 'utf8');
}

main().catch((err) => {
  console.error('design-tokens build failed:', err);
  process.exit(1);
});
