// SPDX-License-Identifier: MIT
// Generated by @rune-langium/codegen — do not edit
// Source namespace: test.cond.navigation

import { z } from 'zod';

// --- rune-codegen runtime helpers (inlined) ---
const runeCheckOneOf = (values: (unknown | undefined | null)[]): boolean =>
  values.filter((v) => v !== undefined && v !== null).length === 1;

const runeCount = (arr: unknown[] | undefined | null): number => arr?.length ?? 0;

const runeAttrExists = (v: unknown): boolean =>
  v !== undefined && v !== null && !(Array.isArray(v) && v.length === 0);
// --- end runtime helpers ---

export const AddressSchema = z.object({
  city: z.string().optional()
});
export type Address = z.infer<typeof AddressSchema>;

export const PartySchema = z
  .object({
    address: AddressSchema.optional()
  })
  .refine((data) => runeAttrExists(data.address?.city), 'CityExists: condition failed in Party');
export type Party = z.infer<typeof PartySchema>;
