// SPDX-License-Identifier: MIT
// Generated by @rune-langium/codegen — do not edit
// Source namespace: test.funcs.recursive

// --- rune-codegen runtime helpers (inlined) ---
const runeValueKey = (value: unknown): string => {
  if (value == null) return 'null';
  if (typeof value !== 'object') return typeof value + ':' + String(value);
  if (Array.isArray(value)) return 'array:' + JSON.stringify(value.map(runeValueKey));
  const tag = Object.prototype.toString.call(value);
  if (/^\[object Temporal\.(PlainDate|PlainTime|PlainDateTime|ZonedDateTime|Instant|PlainYearMonth|PlainMonthDay|Duration)\]$/.test(tag)) return tag + ':' + String(value);
  const fields = value as Record<string, unknown>;
  return 'object:' + JSON.stringify(Object.keys(fields).sort().filter((key) => fields[key] != null).map((key) => [key, runeValueKey(fields[key])]));
};
const runeValueEquals = (left: unknown, right: unknown): boolean => runeValueKey(left) === runeValueKey(right);

const runeCheckOneOf = (values: unknown[]): boolean =>
  values.filter((v) => v !== undefined && v !== null && !(Array.isArray(v) && v.length === 0)).length === 1;

const runeCount = (value: unknown): number => Array.isArray(value) ? value.length : value == null ? 0 : 1;

const runeAttrExists = (v: unknown): boolean =>
  v !== undefined && v !== null && !(Array.isArray(v) && v.length === 0);

const runeToDate = (v: unknown): string | undefined =>
  typeof v === 'string' && /^\d{4}-\d{2}-\d{2}$/.test(v) ? v : undefined;

const runeToTime = (v: unknown): string | undefined =>
  typeof v === 'string' && /^\d{2}:\d{2}:\d{2}(\.\d+)?$/.test(v) ? v : undefined;

const runeToDateTime = (v: unknown): string | undefined =>
  typeof v === 'string' && /^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(\.\d+)?$/.test(v) ? v : undefined;

const runeToZonedDateTime = (v: unknown): string | undefined =>
  typeof v === 'string' && /^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(\.\d+)?(Z|[+-]\d{2}:\d{2})(\[[^\]]+\])?$/.test(v)
    ? v
    : undefined;
// --- end runtime helpers ---


export function Double(input: { n: number }): number {
  input = { ...input, n: ((value) => { if (value == null) throw new Error("Argument 'n' requires a value"); return value; })(input.n) };
  let result: number | undefined;
  result = input.n + input.n;
  if (result == null) throw new Error("Function 'Double' produced no result");
  return result;
}

export function Triple(input: { n: number }): number {
  input = { ...input, n: ((value) => { if (value == null) throw new Error("Argument 'n' requires a value"); return value; })(input.n) };
  let result: number | undefined;
  result = input.n + input.n + input.n;
  if (result == null) throw new Error("Function 'Triple' produced no result");
  return result;
}
