// SPDX-License-Identifier: MIT
// Generated by @rune-langium/codegen — do not edit
// Source namespace: test.rules

// --- rune-codegen runtime helpers (inlined) ---
const runeValueKey = (value: unknown): string => {
  if (value == null) return 'null';
  if (typeof value !== 'object') return typeof value + ':' + String(value);
  if (Array.isArray(value)) return 'array:' + JSON.stringify(value.map(runeValueKey));
  const tag = Object.prototype.toString.call(value);
  if (/^\[object Temporal\.(PlainDate|PlainTime|PlainDateTime|ZonedDateTime|Instant|PlainYearMonth|PlainMonthDay|Duration)\]$/.test(tag)) return tag + ':' + String(value);
  const fields = value as Record<string, unknown>;
  return 'object:' + JSON.stringify(Object.keys(fields).sort().filter((key) => fields[key] != null).map((key) => [key, runeValueKey(fields[key])]));
};
const runeValueEquals = (left: unknown, right: unknown): boolean => runeValueKey(left) === runeValueKey(right);

const runeCheckOneOf = (values: unknown[]): boolean =>
  values.filter((v) => v !== undefined && v !== null && !(Array.isArray(v) && v.length === 0)).length === 1;

const runeCount = (value: unknown): number => Array.isArray(value) ? value.length : value == null ? 0 : 1;

const runeAttrExists = (v: unknown): boolean =>
  v !== undefined && v !== null && !(Array.isArray(v) && v.length === 0);

const runeToDate = (v: unknown): string | undefined =>
  typeof v === 'string' && /^\d{4}-\d{2}-\d{2}$/.test(v) ? v : undefined;

const runeToTime = (v: unknown): string | undefined =>
  typeof v === 'string' && /^\d{2}:\d{2}:\d{2}(\.\d+)?$/.test(v) ? v : undefined;

const runeToDateTime = (v: unknown): string | undefined =>
  typeof v === 'string' && /^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(\.\d+)?$/.test(v) ? v : undefined;

const runeToZonedDateTime = (v: unknown): string | undefined =>
  typeof v === 'string' && /^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(\.\d+)?(Z|[+-]\d{2}:\d{2})(\[[^\]]+\])?$/.test(v)
    ? v
    : undefined;
// --- end runtime helpers ---

export interface PositionShape {
  quantity: number;
  price: number;
  currency: string;
}

export class Position implements PositionShape {
  quantity: number;
  price: number;
  currency: string;

  constructor(data: PositionShape) {
    this.quantity = data.quantity;
    this.price = data.price;
    this.currency = data.currency;
  }

  static from(json: unknown): Position {
    if (!isPosition(json)) {
      throw new TypeError('not a Position: ' + JSON.stringify(json).slice(0, 100));
    }
    return new Position(json as PositionShape);
  }
}

export function isPosition(x: unknown): x is Position {
  if (typeof x !== 'object' || x === null) return false;
  if (typeof (x as Record<string, unknown>).quantity !== 'number') return false;
  if (typeof (x as Record<string, unknown>).price !== 'number') return false;
  if (typeof (x as Record<string, unknown>).currency !== 'string') return false;
  return true;
}


export function validateIsSignificant(position: RuneFuncData<PositionShape>): boolean {
  return position.Position?.quantity * position.Position?.price > 10000;
}

export const runeReportRules = {
  'IsSignificant': { kind: 'eligibility' as const, inputType: 'Position' },
} as const;

type RuneFuncData<T> = T extends readonly (infer I)[]
  ? RuneFuncData<I>[]
  : T extends (...args: never[]) => unknown
    ? never
    : T extends object
      ? { [K in keyof T as T[K] extends (...args: never[]) => unknown ? never : K]: RuneFuncData<T[K]> }
      : T;
