// SPDX-License-Identifier: MIT
// Generated by @rune-langium/codegen — do not edit
// Source namespace: test.rules

// --- rune-codegen runtime helpers (inlined) ---
const runeCheckOneOf = (values: (unknown | undefined | null)[]): boolean =>
  values.filter((v) => v !== undefined && v !== null).length === 1;

const runeCount = (arr: unknown[] | undefined | null): number => arr?.length ?? 0;

const runeAttrExists = (v: unknown): boolean =>
  v !== undefined && v !== null && !(Array.isArray(v) && v.length === 0);
// --- end runtime helpers ---

export interface PositionShape {
  quantity: number;
  price: number;
  currency: string;
}

export class Position implements PositionShape {
  quantity: number;
  price: number;
  currency: string;

  constructor(data: PositionShape) {
    this.quantity = data.quantity as typeof this.quantity;
    this.price = data.price as typeof this.price;
    this.currency = data.currency as typeof this.currency;
  }

  static from(json: unknown): Position {
    if (!isPosition(json)) {
      throw new TypeError('not a Position: ' + JSON.stringify(json).slice(0, 100));
    }
    return new Position(json as PositionShape);
  }
}

export function isPosition(x: unknown): x is Position {
  if (typeof x !== 'object' || x === null) return false;
  if (typeof (x as Record<string, unknown>).quantity !== 'number') return false;
  if (typeof (x as Record<string, unknown>).price !== 'number') return false;
  if (typeof (x as Record<string, unknown>).currency !== 'string') return false;
  return true;
}

export function validateIsSignificant(position: PositionShape): boolean {
  return Position.Position?.quantity * Position.Position?.price > 10000;
}

export const runeReportRules = {
  IsSignificant: { kind: 'eligibility' as const, inputType: 'Position' }
} as const;
// (functions emitted by Phase 8b appear below this line)
