// SPDX-License-Identifier: MIT
// Generated by @rune-langium/codegen — do not edit
// Source namespace: test.cond.onlyexists

import { z } from 'zod';

// --- rune-codegen runtime helpers (inlined) ---
const runeCheckOneOf = (values: (unknown | undefined | null)[]): boolean =>
  values.filter((v) => v !== undefined && v !== null).length === 1;

const runeCount = (arr: unknown[] | undefined | null): number => arr?.length ?? 0;

const runeAttrExists = (v: unknown): boolean =>
  v !== undefined && v !== null && !(Array.isArray(v) && v.length === 0);
// --- end runtime helpers ---

export const HasABCSchema = z
  .object({
    a: z.string().optional(),
    b: z.string().optional(),
    c: z.string().optional()
  })
  .refine((data) => !runeAttrExists(data.c), 'OnlyAB: only [a, b] may exist in HasABC');
export type HasABC = z.infer<typeof HasABCSchema>;
