// SPDX-License-Identifier: MIT
// Generated by @rune-langium/codegen — do not edit
// Source namespace: test.reports

// --- rune-codegen runtime helpers (inlined) ---
const runeCheckOneOf = (values: (unknown | undefined | null)[]): boolean =>
  values.filter((v) => v !== undefined && v !== null).length === 1;

const runeCount = (arr: unknown[] | undefined | null): number => arr?.length ?? 0;

const runeAttrExists = (v: unknown): boolean =>
  v !== undefined && v !== null && !(Array.isArray(v) && v.length === 0);
// --- end runtime helpers ---

export interface TradeShape {
  tradeDate: string;
  notional: number;
}

export class Trade implements TradeShape {
  tradeDate: string;
  notional: number;

  constructor(data: TradeShape) {
    this.tradeDate = data.tradeDate as typeof this.tradeDate;
    this.notional = data.notional as typeof this.notional;
  }

  static from(json: unknown): Trade {
    if (!isTrade(json)) {
      throw new TypeError('not a Trade: ' + JSON.stringify(json).slice(0, 100));
    }
    return new Trade(json as TradeShape);
  }
}

export function isTrade(x: unknown): x is Trade {
  if (typeof x !== 'object' || x === null) return false;
  if (typeof (x as Record<string, unknown>).tradeDate !== 'string') return false;
  if (typeof (x as Record<string, unknown>).notional !== 'number') return false;
  return true;
}

export interface TradeReportShape {
  date: string;
  amount: number;
}

export class TradeReport implements TradeReportShape {
  date: string;
  amount: number;

  constructor(data: TradeReportShape) {
    this.date = data.date as typeof this.date;
    this.amount = data.amount as typeof this.amount;
  }

  static from(json: unknown): TradeReport {
    if (!isTradeReport(json)) {
      throw new TypeError('not a TradeReport: ' + JSON.stringify(json).slice(0, 100));
    }
    return new TradeReport(json as TradeReportShape);
  }
}

export function isTradeReport(x: unknown): x is TradeReport {
  if (typeof x !== 'object' || x === null) return false;
  if (typeof (x as Record<string, unknown>).date !== 'string') return false;
  if (typeof (x as Record<string, unknown>).amount !== 'number') return false;
  return true;
}

export function extractExtractDate(trade: TradeShape): unknown {
  return Trade.Trade?.tradeDate;
}

export function validateIsLargeTrade(trade: TradeShape): boolean {
  return Trade.Trade?.notional > 1000000;
}

export const runeReportRules = {
  ExtractDate: { kind: 'reporting' as const, inputType: 'Trade' },
  IsLargeTrade: { kind: 'eligibility' as const, inputType: 'Trade' }
} as const;
// (functions emitted by Phase 8b appear below this line)
