// SPDX-License-Identifier: FSL-1.1-ALv2
// Copyright (c) 2026 Pradeep Mouli

/**
 * Cloudflare Pages Function: POST /api/parse — fix(019) lazy langium import
 *
 * Server-side `parseWorkspace`. Browser studio POSTs workspace files;
 * function runs Langium parse + builds the index, returns a hydration
 * blob the browser worker can replay locally so subsequent linkDocument
 * requests work without re-parsing.
 *
 * The Langium grammar is registered for `.rosetta` extension only.
 * Incoming files may use `.rune` (studio convention) — we remap URIs
 * internally to `.rosetta` so the service registry can resolve the parser,
 * then expose the original file name in the response.
 */

// Langium services are imported LAZILY inside hydrateUserWorkspace /
// populateDependencyGraph below so an empty-workspace request
// (files: [], curatedBundles: []) avoids the ~1.8 MB langium runtime import
// + createRuneDslServices initialization entirely. Any request that produces
// at least one hydration document (user-parsed or curated-deserialized) pays
// the langium init cost once.
//
// Cross-namespace dep-graph helpers (collectNamespaceDependencies +
// closeNamespaceDependencies) are pure functions over LangiumDocument[]
// — importing them statically pulls in just the AST type guards from
// core's generated/ast.js, not any service runtime.
import type { RosettaModel } from '@rune-langium/core';
import { collectNamespaceDependencies, closeNamespaceDependencies } from '@rune-langium/core';
import { URI, type LangiumDocument, type LangiumSharedCoreServices, type LangiumCoreServices } from 'langium';
import { fetchCuratedBundle, fetchCuratedManifest, fetchCuratedNamespace, CuratedBundleUnavailableError } from '../lib/curated-fetch.js';
import type { CuratedManifest } from '@rune-langium/curated-schema';
import { computeCuratedClosure, closeNamespacesFromManifest } from '../lib/curated-closure.js';
import { readSerializedModelMeta } from '../lib/serialized-model-meta.js';

/**
 * The langium service pair plus the live LangiumDocument set, shared
 * between hydrateUserWorkspace (which produces user docs) and the curated
 * deserialization path (which adds curated docs to the same workspace
 * before walking).
 */
interface WorkspaceContext {
  shared: LangiumSharedCoreServices;
  RuneDsl: LangiumCoreServices;
  userDocs: LangiumDocument[];
}

type ParseRequestBody = {
  files: Array<{ name: string; content: string }>;
  curatedBundles?: Array<{ id: string; version: string }>;
};

/**
 * Env bindings — declared in apps/studio/wrangler.toml (and the deploy-root
 * version generated by build-combined.mjs). Service bindings are passed
 * fetch-shaped via `env.CURATED_MIRROR.fetch(...)` and bypass CF zone
 * routing entirely (no cf-worker header gymnastics, no static-asset
 * fallthrough on /curated/* paths).
 */
interface Env {
  CURATED_MIRROR?: {
    fetch: (input: string | Request, init?: RequestInit) => Promise<Response>;
  };
}

function badRequest(error: string): Response {
  return new Response(JSON.stringify({ ok: false, error }), {
    status: 400,
    headers: { 'Content-Type': 'application/json' }
  });
}

/**
 * Remap a file name to a `.rosetta` URI so the Langium service registry
 * (which only knows about `.rosetta`) can find the correct parser. This
 * URI is INTERNAL to the server-side parse — it's the document handle
 * inside the Langium services, not what we send to the browser.
 *
 * The browser worker keys `deferredModelJson` off the raw filePath
 * (`URI.parse(filePath).toString()`) because that's what
 * `linkDocument(filePath)` from EditorPage sends. The hydration payload
 * therefore emits `doc.uri = filePath` (no scheme), not a `file://` URI.
 */
function toRosettaUri(name: string): URI {
  // Replace trailing extension (e.g. `.rune`) with `.rosetta`. Files without an
  // extension keep their bare name; the Langium service registry uses the
  // remapped suffix to dispatch to the correct parser, and the bare-name case
  // is exercised by tests with paths like `inmemory:///model` that already
  // resolve to the `.rosetta` parser via Langium's default routing.
  const remapped = name.replace(/\.[^./\\]+$/, '.rosetta');
  return URI.parse(`file:///${remapped}`);
}

export const onRequestPost: PagesFunction<Env> = async ({ request, env }) => {
  let body: ParseRequestBody;
  try {
    body = (await request.json()) as ParseRequestBody;
  } catch {
    return badRequest('Malformed JSON');
  }

  if (!Array.isArray(body.files)) {
    return badRequest('files: must be an array');
  }

  // Empty workspace is a legitimate state (new tab, no user files yet, or
  // user just opened the studio without loading anything). Return an empty
  // hydrationState rather than 400 — clients shouldn't have to special-case
  // this around their normal parse flow. The studio's parseWorkspaceFiles
  // calls /api/parse on every debounced edit, including before any user
  // file exists.
  if (body.files.length === 0 && (!Array.isArray(body.curatedBundles) || body.curatedBundles.length === 0)) {
    return new Response(
      JSON.stringify({
        ok: true,
        models: [],
        deferredExports: [],
        errors: {},
        hydrationState: { documents: [] },
        dependencyGraph: {}
      }),
      { status: 200, headers: { 'Content-Type': 'application/json' } }
    );
  }

  try {
    const errors: Record<string, string[]> = {};
    // Cross-namespace dep graph (spec 2026-05-14 §5.2). Keys are namespace
    // names (e.g. "cdm.trade"); values are the transitive dep closure
    // including the source itself, sorted for stable response bytes.
    // Populated by the unified hydrate-and-walk pass below: user files come
    // pre-built from parseUserFiles, curated docs are deserialized via
    // JsonSerializer.deserialize using the same services, and the combined
    // workspace is re-linked so cross-bundle $refs resolve before walking.
    const dependencyGraph: Record<string, string[]> = {};
    const documentsForHydration: Array<{
      uri: string;
      content: string;
      serializedModel: string;
      exports: Array<{ type: string; name: string; path: string }>;
      /**
       * Set on curated bundle entries; absent on user-file entries. The
       * studio uses this to mark workspace files refOnly without parsing
       * URI prefixes (which would false-positive for user paths like
       * `${bundleId}/foo.rosetta`).
       */
      bundleId?: string;
    }> = [];

    // The deferredExports summary mirrors what handleParseWorkspace produces:
    // ONE entry per file (not per namespace). A single namespace can span
    // multiple .rosetta files (e.g. cdm.base.datetime is split across
    // -type/-enum/-func), and the studio's nodeIdToFilePath map needs each
    // exported name to point at the file that actually declares it so
    // linkDocument hits the right deferred-model JSON. Collapsing per
    // namespace was the root cause of "curated nodes show empty in
    // Structure/Inspector" — every node-id mapped to the first file's
    // filePath and linkDocument materialized the wrong AST.
    const deferredExportsList: Array<{
      filePath: string;
      namespace: string;
      entries: Array<{ type: string; name: string }>;
    }> = [];

    // User files run through Langium parse + serialize. The returned
    // context (full service pair + LangiumDocument[]) is reused below for
    // the unified dep-graph computation so we don't double-import langium.
    let workspaceContext: WorkspaceContext | undefined;
    if (body.files.length > 0) {
      workspaceContext = await hydrateUserWorkspace(body.files, errors, documentsForHydration, deferredExportsList);
    }

    // Seed namespaces for the curated closure: the namespaces the user files
    // import. Hoisted here (before the bundle loop) so the manifest fast-path
    // can use them when computing which per-namespace artifacts to fetch.
    const seeds = collectUserSeedNamespaces(workspaceContext?.userDocs ?? []);

    // Fetch curated bundles via the CURATED_MIRROR service binding so the
    // subrequest bypasses CF same-zone routing. Falls back to global fetch
    // when the binding isn't present (local dev, tests, smoke probes).
    const curatedFetcher = env?.CURATED_MIRROR
      ? (url: string, init?: RequestInit) => env.CURATED_MIRROR!.fetch(url, init)
      : undefined;
    // Accumulators bridging the bundle loop and the dep-graph block below.
    // manifestClosureNamespaces collects the closure the manifest fast-path
    // already computed (from the precomputed graph, no doc parsing) so the
    // dep-graph block can reuse it instead of re-deriving it. anyV1Fallback
    // flags that at least one bundle took the whole-bundle path, in which case
    // the closure must be derived from the loaded docs.
    const manifestClosureNamespaces = new Set<string>();
    let anyV1Fallback = false;
    if (Array.isArray(body.curatedBundles) && body.curatedBundles.length > 0) {
      for (const bundle of body.curatedBundles) {
        try {
          // The manifest fetch is the entry point for the fast-path, but it must
          // NOT become a new single point of failure: if manifest.json is
          // transiently unavailable/malformed while latest.serialized.json.gz is
          // still healthy, fall back to the whole-bundle path rather than 502ing
          // every curated request (Codex P1). Only a manifest-fetch failure is
          // swallowed here; a per-namespace artifact failure inside the fast-path
          // still surfaces as 502 (the manifest referenced an artifact that
          // doesn't exist — a genuinely broken publish).
          let manifest: CuratedManifest | null = null;
          try {
            manifest = await fetchCuratedManifest(bundle.id, bundle.version, curatedFetcher);
          } catch (manifestErr) {
            if (manifestErr instanceof CuratedBundleUnavailableError) {
              console.error('curated-fetch manifest_unavailable_falling_back', {
                bundleId: bundle.id,
                version: bundle.version,
                status: manifestErr.status
              });
              manifest = null; // → whole-bundle fallback below
            } else {
              throw manifestErr;
            }
          }
          if (manifest && manifest.namespaces && Object.keys(manifest.namespaces).length > 0) {
            // Manifest fast-path: fetch ONLY the user's closure, never the whole bundle.
            const nsGraph = manifest.namespaces;
            const closure = closeNamespacesFromManifest(seeds, nsGraph);
            for (const ns of closure) manifestClosureNamespaces.add(ns);
            // Fetch the closure's per-namespace artifacts CONCURRENTLY. A large
            // closure (e.g. fpml.consolidated.* pulls ~40 namespaces) was ~12s
            // serial; the fetches are independent network I/O, so Promise.all
            // collapses that to roughly the slowest single fetch. Results are
            // consumed in a stable order so deferredExports/hydration ordering
            // is deterministic across requests.
            const closureNs = [...closure].filter((ns) => nsGraph[ns]);
            const fetchedPerNs = await Promise.all(
              closureNs.map((ns) =>
                fetchCuratedNamespace(bundle.id, bundle.version, nsGraph[ns]!.artifact, curatedFetcher)
              )
            );
            for (const nsDocs of fetchedPerNs) {
              for (const doc of nsDocs) {
                documentsForHydration.push({ ...doc, bundleId: bundle.id });
                // Per-FILE entry so node-id → filePath → hydrationState linking stays correct.
                mergeCuratedDocIntoDeferredExports(doc, deferredExportsList);
              }
            }
            // List every OTHER curated namespace so the explorer shows the full corpus.
            // These are list-only (not hydrated): filePath uses the bundle-prefixed synthetic
            // path so split('/')[0] === bundle.id, consistent with closure entries.
            // Expanding one would re-parse with that namespace pulled into closure.
            for (const [ns, entry] of Object.entries(nsGraph)) {
              if (closure.has(ns)) continue; // closure namespaces already have per-file entries
              deferredExportsList.push({
                filePath: `${bundle.id}/${ns}`, // bundle-prefixed synthetic path: split('/')[0] === bundle.id;
                                                 // not a hydrated doc (list-only) — expanding such a node is a
                                                 // soft no-op until the namespace is imported (pulled into closure).
                namespace: ns,
                entries: entry.exports.map((e) => ({ type: e.type, name: e.name }))
              });
            }
          } else {
            // v1 fallback: no per-namespace graph — fetch the whole bundle (existing path).
            anyV1Fallback = true;
            const curatedDocs = await fetchCuratedBundle(bundle.id, bundle.version, curatedFetcher);
            for (const doc of curatedDocs) {
              // Stamp the bundle id onto the hydration document explicitly so
              // the studio doesn't have to infer bundle membership from the
              // URI prefix (Copilot review: that inference was silently
              // coupled to curated-fetch's URI convention and false-positive'd
              // for user files saved under `${bundleId}/...` paths). The
              // field is optional on the hydration shape so user-file
              // entries omit it.
              documentsForHydration.push({ ...doc, bundleId: bundle.id });
              // Surface curated namespaces in the deferredExports response so
              // the studio's namespace explorer / graph view (which reads from
              // deferredExports) lists CDM/FpML/rune-dsl entries alongside
              // user-file namespaces (Codex P2 review). Without this the corpus
              // hydrates correctly but its read-only nodes are invisible until
              // an editor link triggers linkDocument and pulls them on-demand.
              mergeCuratedDocIntoDeferredExports(doc, deferredExportsList);
            }
          }
        } catch (err) {
          if (err instanceof CuratedBundleUnavailableError) {
            return new Response(
              JSON.stringify({
                ok: false,
                error: 'curated_bundle_unavailable',
                bundleId: err.bundleId,
                version: err.version,
                upstreamStatus: err.status
              }),
              { status: 502, headers: { 'Content-Type': 'application/json' } }
            );
          }
          throw err;
        }
      }
    }

    // Cross-namespace dep-graph (spec 2026-05-14 §5.2). Runs over the full
    // workspace — user-parsed docs (kept live in workspaceContext) plus
    // curated docs (deserialized here from their serializedModel strings)
    // — so the modal's auto-select cascade resolves cross-bundle refs
    // (cdm.trade → cdm.base.datetime, etc.) without re-fetching anything.
    // For empty-workspace requests (no user files, no curated bundles),
    // nothing was loaded and the dep graph stays empty (early-returned above).
    if (documentsForHydration.length > 0) {
      // Manifest fast-path already produced the authoritative curated closure from
      // the precomputed graph (no doc parsing). Only fall back to the serialized-
      // import walk when a v1 (whole-bundle) bundle was loaded — then we must derive
      // the closure from the docs. computeCuratedClosure over closure-only docs would
      // otherwise just re-parse what we already know.
      const closure = anyV1Fallback
        ? computeCuratedClosure(
            seeds,
            documentsForHydration
              .filter((d) => d.bundleId !== undefined)
              .map((d) => ({ uri: d.uri, serializedModel: d.serializedModel }))
          )
        : manifestClosureNamespaces;
      await populateDependencyGraph(documentsForHydration, workspaceContext, dependencyGraph, closure);
    }

    // Raw Langium AST nodes have circular $container refs and cannot be
    // JSON-serialized. The HTTP response carries the serialized AST inside
    // `hydrationState.documents[].serializedModel` (Langium JSON serializer
    // output). `models` is intentionally empty; `parsedModels` is omitted
    // entirely — the browser worker (Task 0.5) will reconstruct any model list
    // it needs from hydrationState.documents.

    return new Response(
      stringifyWithBigInt({
        ok: true,
        models: [],
        // parsedModels intentionally absent — server cannot send Langium ASTs
        // (circular $container refs). Task 0.5 rebuilds this client-side from
        // hydrationState.documents if needed.
        deferredExports: deferredExportsList.map(({ filePath: entryFilePath, namespace, entries }) => ({
          filePath: entryFilePath,
          namespace,
          exports: entries
        })),
        errors,
        hydrationState: { documents: documentsForHydration },
        dependencyGraph
      }),
      {
        status: 200,
        headers: { 'Content-Type': 'application/json' }
      }
    );
  } catch (err) {
    return new Response(
      JSON.stringify({
        ok: false,
        error: err instanceof Error ? err.message : String(err)
      }),
      { status: 500, headers: { 'Content-Type': 'application/json' } }
    );
  }
};

/**
 * Hydrate user-authored .rune files into a Langium workspace: parse via the
 * grammar, build + link, then serialize each model into JSON for the
 * response's `hydrationState`. Returns the live LangiumDocument[] + services
 * so the caller can reuse them for the cross-namespace dep-graph pass
 * (which deserializes curated docs into the same workspace before walking).
 *
 * Lazy-imports `@rune-langium/core` so requests with no work (no user
 * files AND no curated bundles) don't pay the ~1.8 MB bundle init cost.
 *
 * Mutates the passed-in `errors`, `documentsForHydration`, and
 * `deferredExportsList` collections; returns the services + docs.
 */
async function hydrateUserWorkspace(
  files: ReadonlyArray<{ name: string; content: string }>,
  errors: Record<string, string[]>,
  documentsForHydration: Array<{
    uri: string;
    content: string;
    serializedModel: string;
    exports: Array<{ type: string; name: string; path: string }>;
  }>,
  deferredExportsList: Array<{ filePath: string; namespace: string; entries: Array<{ type: string; name: string }> }>
): Promise<WorkspaceContext> {
  const [{ createRuneDslServices }, { EmptyFileSystem }] = await Promise.all([
    import('@rune-langium/core'),
    import('langium')
  ]);
  const { RuneDsl, shared } = createRuneDslServices(EmptyFileSystem);
  const factory = shared.workspace.LangiumDocumentFactory;
  const builder = shared.workspace.DocumentBuilder;

  const docs = files.map((f) => factory.fromString(f.content, toRosettaUri(f.name)));
  await builder.build(docs, { validation: false });

  for (let i = 0; i < docs.length; i++) {
    const doc = docs[i];
    const filePath = files[i].name;
    const parseErrors = doc.parseResult.parserErrors.map((e) => e.message);
    if (parseErrors.length > 0) {
      errors[filePath] = parseErrors;
    }
    const model = doc.parseResult.value as RosettaModel | undefined;
    if (!model) continue;

    // Copy CST source text into `$cstText` on Function/Data/Choice
    // condition + expression nodes BEFORE serializing. The visual editor
    // reads `$cstText` to render expression cells (functions with
    // conditions, function bodies, function expressions). Without this
    // pre-serialization step, the deserialized AST has no source text
    // — langium's `$cstNode` lives only on the live AST, not in the
    // serialized JSON — and the visual editor renders affected
    // expressions as blank even though the parse succeeded (Codex P2).
    //
    // Mirrors apps/studio/src/workers/parser-worker.ts:preserveCstText,
    // which the browser-side parse path already calls. Adding it here
    // keeps the routed parse output equivalent to the in-worker output.
    preserveCstText(model);

    // textRegions + refText preserve text-region offsets so language-
    // server features (e.g. go-to-definition, hover, code-action ranges)
    // can map AST nodes back to source spans after deserialization.
    // The BigInt replacer keeps large numeric literals JSON-safe — the
    // outer stringifyWithBigInt also handles them, but doing it inside
    // the langium serializer is more efficient (avoids one re-scan of
    // the embedded model JSON).
    const serializedModel = RuneDsl.serializer.JsonSerializer.serialize(model, {
      refText: true,
      textRegions: true,
      replacer: (_key, value, defaultReplacer) =>
        typeof value === 'bigint' ? Number(value) : defaultReplacer(_key, value)
    });
    const rawName = model.name as string;
    const namespace = rawName ? rawName.replace(/^"|"$/g, '') : '';

    const exports: Array<{ type: string; name: string; path: string }> = [];
    if (namespace) {
      for (const elem of model.elements) {
        const e = elem as { $type: string; name?: string };
        if (e.name) {
          exports.push({ type: e.$type, name: e.name, path: `${namespace}.${e.name}` });
        }
      }
    }

    documentsForHydration.push({
      uri: filePath,
      content: files[i].content,
      serializedModel,
      exports
    });

    if (namespace) {
      // Emit ONE entry per file so the studio's nodeIdToFilePath builder
      // can route each name to the file that declares it. See the comment
      // in handlePost where deferredExportsList is initialized.
      deferredExportsList.push({
        filePath,
        namespace,
        entries: exports.map((e) => ({ type: e.type, name: e.name }))
      });
    }
  }

  return { shared, RuneDsl, userDocs: docs };
}

/**
 * Walk the parsed RosettaModel and copy `$cstNode.text` into a sibling
 * `$cstText` property on Function-body parts, condition nodes, and
 * expression nodes. Mirrors `preserveCstText` in
 * apps/studio/src/workers/parser-worker.ts — keep the two implementations
 * in sync.
 *
 * Why this is needed: the visual editor's expression cells render from
 * `$cstText` (a serializable string property) rather than `$cstNode`
 * (the live CST tree, which is non-serializable and lost during JSON
 * round-trip). The in-browser parse path attached `$cstText` before
 * postMessage; the server-side parse path needs the same step so its
 * downstream hydration payload contains the same source text.
 */
/* eslint-disable @typescript-eslint/no-explicit-any */
function preserveCstText(model: any): void {
  for (const elem of model?.elements ?? []) {
    if (elem.$type === 'RosettaFunction') {
      for (const arr of [elem.shortcuts, elem.conditions, elem.operations, elem.postConditions]) {
        for (const part of arr ?? []) {
          if (part?.$cstNode?.text) {
            part.$cstText = part.$cstNode.text;
          }
          if (part?.expression?.$cstNode?.text) {
            part.expression.$cstText = part.expression.$cstNode.text;
          }
        }
      }
    }
    if (elem.conditions) {
      for (const cond of elem.conditions) {
        if (cond?.$cstNode?.text) {
          cond.$cstText = cond.$cstNode.text;
        }
        if (cond?.expression?.$cstNode?.text) {
          cond.expression.$cstText = cond.expression.$cstNode.text;
        }
      }
    }
  }
}
/* eslint-enable @typescript-eslint/no-explicit-any */

/**
 * Extract the curated doc's namespace from its serialized model and append
 * a per-FILE entry to the deferredExports list. Mutates the passed list in
 * place to match the same shape the in-browser parser-worker produces
 * (apps/studio/src/workers/parser-worker.ts:handleParseWorkspace emits one
 * entry per file, not per namespace).
 *
 * Why per-file and not per-namespace: a single namespace (e.g.
 * `cdm.base.datetime`) can be split across multiple `.rosetta` files
 * (`-type.rosetta`, `-enum.rosetta`, `-func.rosetta`). The earlier
 * per-namespace collapse would assign ALL of that namespace's exports to
 * whichever file was iterated first, so the studio's nodeIdToFilePath
 * map (EditorPage.tsx) would route every linkDocument call to the wrong
 * file. Cross-file linking then never fires for the file that actually
 * declares the clicked type, and curated nodes appear bodiless because
 * their AST never gets hydrated.
 *
 * Namespace comes from the top-level `name` field of the Langium-serialized
 * RosettaModel. We slice off the model preamble and run a small regex
 * rather than JSON.parse the whole body — the model bodies are large
 * (~kilobytes each) but `name` always appears within the first ~256 bytes.
 */
function mergeCuratedDocIntoDeferredExports(
  doc: { uri: string; serializedModel: string; exports: Array<{ type: string; name: string; path: string }> },
  deferredExportsList: Array<{ filePath: string; namespace: string; entries: Array<{ type: string; name: string }> }>
): void {
  const preamble = doc.serializedModel.slice(0, 256);
  const nameMatch = /"name"\s*:\s*"([^"]+)"/.exec(preamble);
  if (!nameMatch) return;
  const namespace = nameMatch[1].replace(/^"|"$/g, '');
  if (!namespace) return;

  deferredExportsList.push({
    filePath: doc.uri,
    namespace,
    entries: doc.exports.map((e) => ({ type: e.type, name: e.name }))
  });
}

/**
 * `JSON.stringify` throws on BigInt by default. The Langium parser produces
 * BigInt values for some numeric literals in the Rune grammar (e.g. very
 * large integers parsed as bigint). Those leak into `documentsForHydration`
 * via `serializedModel` and `exports`, so we need a replacer that converts
 * them to strings. Browser-side deserialization treats them as strings —
 * acceptable because nothing on the client currently depends on numeric
 * comparison of these values.
 */
function stringifyWithBigInt(value: unknown): string {
  return JSON.stringify(value, (_key, v) => (typeof v === 'bigint' ? v.toString() : v));
}

/**
 * Seed namespaces for the curated closure = the namespaces the user files
 * import. Read from the already-parsed user models (no link needed).
 * Exported for unit testing.
 */
export function collectUserSeedNamespaces(
  userDocs: ReadonlyArray<{ parseResult?: { value?: unknown } }>
): Set<string> {
  const seeds = new Set<string>();
  for (const doc of userDocs) {
    const model = doc.parseResult?.value as { imports?: Array<{ importedNamespace?: unknown }> } | undefined;
    if (!model || !Array.isArray(model.imports)) continue;
    for (const imp of model.imports) {
      if (typeof imp.importedNamespace === 'string' && imp.importedNamespace.length > 0) {
        seeds.add(imp.importedNamespace);
      }
    }
  }
  return seeds;
}

/**
 * Compute the cross-namespace dep graph (spec 2026-05-14 §5.2) over the
 * full hydration set — user-parsed docs (already live in workspaceContext)
 * plus curated docs (deserialized here from `serializedModel` strings via
 * the same pattern apps/studio/src/workers/codegen-worker.ts uses).
 *
 * The combined set is re-linked through DocumentBuilder.build so cross-
 * bundle `$ref` targets resolve before the walker reads them. Each
 * namespace gets its transitive closure (via closeNamespaceDependencies)
 * sorted into a stable string[] in `dependencyGraph[ns]`.
 *
 * If `workspaceContext` is undefined (curated-only request), we lazy-import
 * langium services here so empty-workspace requests still skip the cost.
 */
async function populateDependencyGraph(
  documentsForHydration: ReadonlyArray<{
    uri: string;
    serializedModel: string;
    bundleId?: string;
  }>,
  workspaceContext: WorkspaceContext | undefined,
  dependencyGraph: Record<string, string[]>,
  closureNamespaces: ReadonlySet<string>
): Promise<void> {
  // Fail-soft: a missing/partial dep graph degrades the modal's auto-cascade
  // hints but never breaks /api/parse's primary hydration contract. Any
  // exception here (malformed serializedModel, deserializer schema drift,
  // builder.build chokepoint) leaves dependencyGraph empty and continues.
  try {
    let context = workspaceContext;
    if (!context) {
      const [{ createRuneDslServices }, { EmptyFileSystem }] = await Promise.all([
        import('@rune-langium/core'),
        import('langium')
      ]);
      const { RuneDsl, shared } = createRuneDslServices(EmptyFileSystem);
      context = { shared, RuneDsl, userDocs: [] };
    }
    const factory = context.shared.workspace.LangiumDocumentFactory;
    const builder = context.shared.workspace.DocumentBuilder;

    // Hydrate curated docs into LangiumDocuments. User docs are already in
    // the workspace from hydrateUserWorkspace; we identify curated entries by
    // `bundleId` presence (set in the curated loop, omitted on user files).
    //
    // Lazy-link: only deserialize+link curated docs whose namespace is in the
    // user's reference closure. Reading the namespace from serialized JSON is
    // cheap (no Langium deserialize) — skipping out-of-closure docs before
    // paying the deserialize+link cost is what brings curated-bundle requests
    // back under CF's CPU limit (error 1102).
    const curatedDocs: LangiumDocument[] = [];
    for (const entry of documentsForHydration) {
      if (entry.bundleId === undefined) continue;
      const meta = readSerializedModelMeta(entry.serializedModel);
      if (!meta || !closureNamespaces.has(meta.namespace)) continue;
      try {
        const model = context.RuneDsl.serializer.JsonSerializer.deserialize(entry.serializedModel) as RosettaModel;
        const doc = factory.fromModel(model, URI.parse(entry.uri));
        curatedDocs.push(doc);
      } catch {
        // Skip individual malformed entries — the rest of the workspace
        // still produces a useful (partial) dep graph.
      }
    }

    if (curatedDocs.length > 0) {
      // Re-link combined workspace so cross-bundle $refs resolve. Validation
      // off: same flag hydrateUserWorkspace passed when it built user docs.
      await builder.build([...context.userDocs, ...curatedDocs], { validation: false });
    }

    const allDocs: LangiumDocument[] = [...context.userDocs, ...curatedDocs];
    if (allDocs.length === 0) return;

    const directDeps = collectNamespaceDependencies(allDocs);
    for (const namespace of directDeps.keys()) {
      const closure = closeNamespaceDependencies(namespace, directDeps);
      dependencyGraph[namespace] = Array.from(closure).sort();
    }
  } catch (err) {
    console.warn('[api/parse] dep-graph computation failed; response will omit dependencyGraph entries.', err);
  }
}
