// SPDX-License-Identifier: FSL-1.1-ALv2
// Copyright (c) 2026 Pradeep Mouli

/**
 * Cloudflare Pages Function: POST /api/parse — fix(019) lazy langium import
 *
 * Server-side `parseWorkspace`. Browser studio POSTs workspace files;
 * function runs Langium parse + builds the index, returns a hydration
 * blob the browser worker can replay locally so subsequent linkDocument
 * requests work without re-parsing.
 *
 * The Langium grammar is registered for `.rosetta` extension only.
 * Incoming files may use `.rune` (studio convention) — we remap URIs
 * internally to `.rosetta` so the service registry can resolve the parser,
 * then expose the original file name in the response.
 */

// Langium services are imported LAZILY inside hydrateUserWorkspace so an
// empty-workspace request (files: [], curatedBundles: []) avoids the ~1.8 MB
// langium runtime import + createRuneDslServices initialization entirely.
// Any request with user files pays the langium init cost once.
import type { RosettaModel } from '@rune-langium/core';
import {
  qualifiedExportPath,
  serializeRuneModel,
  runeBigIntReplacer,
  preserveCstText,
  namespaceFromModelName,
  collectNamespaceDependencies
} from '@rune-langium/core';
import { URI, type LangiumDocument, type LangiumSharedCoreServices, type LangiumCoreServices } from 'langium';
import {
  fetchCuratedManifest,
  fetchCuratedNamespace,
  CuratedBundleUnavailableError
} from '../lib/curated-fetch.js';
import { closeNamespacesFromManifest, buildDependencyGraph, expandWildcard } from '../lib/curated-closure.js';
import { readSerializedModelMeta } from '../lib/serialized-model-meta.js';

/**
 * The langium service pair plus the live LangiumDocument set, shared
 * between hydrateUserWorkspace (which produces user docs) and the curated
 * deserialization path (which adds curated docs to the same workspace
 * before walking).
 */
interface WorkspaceContext {
  shared: LangiumSharedCoreServices;
  RuneDsl: LangiumCoreServices;
  userDocs: LangiumDocument[];
}

type ParseRequestBody = {
  files: Array<{ name: string; content: string }>;
  curatedBundles?: Array<{ id: string; version: string }>;
  /** Fully-qualified namespaces to hydrate beyond the user's import closure
   *  (on-demand curated browsing). Unioned into the closure seeds; names not
   *  present in a loaded bundle's manifest are ignored. */
  hydrateNamespaces?: string[];
};

/**
 * Env bindings — declared in apps/studio/wrangler.toml (and the deploy-root
 * version generated by build-combined.mjs). Service bindings are passed
 * fetch-shaped via `env.CURATED_MIRROR.fetch(...)` and bypass CF zone
 * routing entirely (no cf-worker header gymnastics, no static-asset
 * fallthrough on /curated/* paths).
 */
interface Env {
  CURATED_MIRROR?: {
    fetch: (input: string | Request, init?: RequestInit) => Promise<Response>;
  };
}

function badRequest(error: string): Response {
  return new Response(JSON.stringify({ ok: false, error }), {
    status: 400,
    headers: { 'Content-Type': 'application/json' }
  });
}

/**
 * Remap a file name to a `.rosetta` URI so the Langium service registry
 * (which only knows about `.rosetta`) can find the correct parser. This
 * URI is INTERNAL to the server-side parse — it's the document handle
 * inside the Langium services, not what we send to the browser.
 *
 * The browser worker keys `deferredModelJson` off the raw filePath
 * (`URI.parse(filePath).toString()`) because that's what
 * `linkDocument(filePath)` from EditorPage sends. The hydration payload
 * therefore emits `doc.uri = filePath` (no scheme), not a `file://` URI.
 */
function toRosettaUri(name: string): URI {
  // Replace trailing extension (e.g. `.rune`) with `.rosetta`. Files without an
  // extension keep their bare name; the Langium service registry uses the
  // remapped suffix to dispatch to the correct parser, and the bare-name case
  // is exercised by tests with paths like `inmemory:///model` that already
  // resolve to the `.rosetta` parser via Langium's default routing.
  const remapped = name.replace(/\.[^./\\]+$/, '.rosetta');
  return URI.parse(`file:///${remapped}`);
}

export const onRequestPost: PagesFunction<Env> = async ({ request, env }) => {
  let body: ParseRequestBody;
  try {
    body = (await request.json()) as ParseRequestBody;
  } catch {
    return badRequest('Malformed JSON');
  }

  if (!Array.isArray(body.files)) {
    return badRequest('files: must be an array');
  }

  // Empty workspace is a legitimate state (new tab, no user files yet, or
  // user just opened the studio without loading anything). Return an empty
  // hydrationState rather than 400 — clients shouldn't have to special-case
  // this around their normal parse flow. The studio's parseWorkspaceFiles
  // calls /api/parse on every debounced edit, including before any user
  // file exists.
  if (body.files.length === 0 && (!Array.isArray(body.curatedBundles) || body.curatedBundles.length === 0)) {
    return new Response(
      JSON.stringify({
        ok: true,
        models: [],
        deferredExports: [],
        errors: {},
        hydrationState: { documents: [] },
        dependencyGraph: {}
      }),
      { status: 200, headers: { 'Content-Type': 'application/json' } }
    );
  }

  try {
    const errors: Record<string, string[]> = {};
    // Cross-namespace dep graph (spec 2026-05-14 §5.2). Keys are namespace
    // names (e.g. "cdm.trade"); values are the transitive dep closure
    // including the source itself, sorted for stable response bytes.
    // Populated by the unified hydrate-and-walk pass below: user files come
    // pre-built from parseUserFiles, curated docs are deserialized via
    // JsonSerializer.deserialize using the same services, and the combined
    // workspace is re-linked so cross-bundle $refs resolve before walking.
    const dependencyGraph: Record<string, string[]> = {};
    const documentsForHydration: Array<{
      uri: string;
      content: string;
      serializedModel: string;
      exports: Array<{ type: string; name: string; path: string }>;
      /**
       * Set on curated bundle entries; absent on user-file entries. The
       * studio uses this to mark workspace files refOnly without parsing
       * URI prefixes (which would false-positive for user paths like
       * `${bundleId}/foo.rosetta`).
       */
      bundleId?: string;
    }> = [];

    // The deferredExports summary mirrors what handleParseWorkspace produces:
    // ONE entry per file (not per namespace). A single namespace can span
    // multiple .rosetta files (e.g. cdm.base.datetime is split across
    // -type/-enum/-func), and the studio's nodeIdToFilePath map needs each
    // exported name to point at the file that actually declares it so
    // linkDocument hits the right deferred-model JSON. Collapsing per
    // namespace was the root cause of "curated nodes show empty in
    // Structure/Inspector" — every node-id mapped to the first file's
    // filePath and linkDocument materialized the wrong AST.
    const deferredExportsList: Array<{
      filePath: string;
      namespace: string;
      entries: Array<{ type: string; name: string }>;
    }> = [];

    // User files run through Langium parse + serialize. The returned
    // context (full service pair + LangiumDocument[]) is reused below for
    // the unified dep-graph computation so we don't double-import langium.
    let workspaceContext: WorkspaceContext | undefined;
    if (body.files.length > 0) {
      workspaceContext = await hydrateUserWorkspace(body.files, errors, documentsForHydration, deferredExportsList);
    }

    // Seed namespaces for the curated closure: the namespaces the user files
    // import. Hoisted here (before the bundle loop) so the manifest fast-path
    // can use them when computing which per-namespace artifacts to fetch.
    const seeds = collectUserSeedNamespaces(workspaceContext?.userDocs ?? []);
    // On-demand hydration: the browser may request namespaces beyond the user's
    // import closure (curated browsing). Union them into the seeds; each bundle's
    // closure walk picks up the ones present in its own manifest and pulls their
    // transitive deps (closeNamespacesFromManifest ignores unknown seeds).
    const requestedHydration = Array.isArray(body.hydrateNamespaces) ? body.hydrateNamespaces : [];
    for (const ns of requestedHydration) {
      if (typeof ns === 'string') seeds.add(ns);
    }

    // Fetch curated bundles via the CURATED_MIRROR service binding so the
    // subrequest bypasses CF same-zone routing. Falls back to global fetch
    // when the binding isn't present (local dev, tests, smoke probes).
    const curatedFetcher = env?.CURATED_MIRROR
      ? (url: string, init?: RequestInit) => env.CURATED_MIRROR!.fetch(url, init)
      : undefined;
    // Accumulators bridging the bundle loop and the dep-graph block below.
    // manifestClosureNamespaces collects the closure the manifest fast-path
    // computed (from the precomputed graph, no doc parsing) so the dep-graph
    // block can reuse it instead of re-deriving it. The manifest is required —
    // a missing/empty manifest returns 502; there is no whole-bundle fallback.
    const manifestClosureNamespaces = new Set<string>();
    // Direct curated→curated edges per closure namespace, read from the
    // precomputed manifest graph (NO deserialize/link). Feeds buildDependencyGraph.
    const curatedDirectDeps = new Map<string, Set<string>>();
    if (Array.isArray(body.curatedBundles) && body.curatedBundles.length > 0) {
      for (const bundle of body.curatedBundles) {
        try {
          const manifest = await fetchCuratedManifest(bundle.id, bundle.version, curatedFetcher);
          if (!manifest?.namespaces || Object.keys(manifest.namespaces).length === 0) {
            return new Response(
              JSON.stringify({
                ok: false,
                error: 'curated_manifest_missing',
                bundleId: bundle.id,
                version: bundle.version
              }),
              { status: 502, headers: { 'Content-Type': 'application/json' } }
            );
          }
          // Manifest fast-path: fetch ONLY the user's closure, never the whole bundle.
          const nsGraph = manifest.namespaces;
          const closure = closeNamespacesFromManifest(seeds, nsGraph);
          for (const ns of closure) manifestClosureNamespaces.add(ns);
          // Record precomputed curated→curated edges for the dep graph (no link).
          for (const ns of closure) {
            const entry = nsGraph[ns];
            if (!entry) continue;
            const targets = new Set<string>();
            for (const raw of entry.deps) {
              for (const t of expandWildcard(raw, closure)) targets.add(t);
            }
            curatedDirectDeps.set(ns, targets);
          }
          const closureNs = [...closure].filter((ns) => nsGraph[ns]);
          const FETCH_CONCURRENCY = 8;
          for (let i = 0; i < closureNs.length; i += FETCH_CONCURRENCY) {
            const window = closureNs.slice(i, i + FETCH_CONCURRENCY);
            const fetchedPerNs = await Promise.all(
              window.map((ns) =>
                fetchCuratedNamespace(bundle.id, bundle.version, nsGraph[ns]!.artifact, curatedFetcher)
              )
            );
            for (const nsDocs of fetchedPerNs) {
              for (const doc of nsDocs) {
                documentsForHydration.push({ ...doc, bundleId: bundle.id });
                mergeCuratedDocIntoDeferredExports(doc, deferredExportsList);
              }
            }
          }
          // List every OTHER curated namespace so the explorer shows the full corpus.
          for (const [ns, entry] of Object.entries(nsGraph)) {
            if (closure.has(ns)) continue;
            deferredExportsList.push({
              filePath: `${bundle.id}/${ns}`,
              namespace: ns,
              entries: entry.exports.map((e) => ({ type: e.type, name: e.name }))
            });
          }
        } catch (err) {
          if (err instanceof CuratedBundleUnavailableError) {
            return new Response(
              JSON.stringify({
                ok: false,
                error: 'curated_bundle_unavailable',
                bundleId: err.bundleId,
                version: err.version,
                upstreamStatus: err.status
              }),
              { status: 502, headers: { 'Content-Type': 'application/json' } }
            );
          }
          throw err;
        }
      }
    }

    // Build the cross-namespace dep graph from precomputed manifest edges +
    // user import declarations. No curated deserialize/link — see design
    // 2026-06-26-curated-dep-graph-no-link.
    if (documentsForHydration.length > 0) {
      const userModels: Array<{ namespace: string; imports: string[] }> = [];
      for (const entry of documentsForHydration) {
        if (entry.bundleId !== undefined) continue; // curated entries carry bundleId; user docs don't
        const meta = readSerializedModelMeta(entry.serializedModel);
        if (meta) userModels.push(meta);
      }
      const allNamespaces = new Set<string>(manifestClosureNamespaces);
      for (const m of userModels) allNamespaces.add(m.namespace);
      // Resolved user→user edges from the already-built user docs (cheap — user
      // files only, NOT the curated corpus, so the 128 MB OOM stays fixed).
      // Captures qualified cross-namespace refs the DSL resolves via global
      // scope without an import, which userModels.imports alone would miss.
      const userResolvedDeps = collectNamespaceDependencies(workspaceContext?.userDocs ?? []);
      Object.assign(
        dependencyGraph,
        buildDependencyGraph(userModels, curatedDirectDeps, allNamespaces, userResolvedDeps)
      );
    }

    // Raw Langium AST nodes have circular $container refs and cannot be
    // JSON-serialized. The HTTP response carries the serialized AST inside
    // `hydrationState.documents[].serializedModel` (Langium JSON serializer
    // output). `models` is intentionally empty; `parsedModels` is omitted
    // entirely — the browser worker (Task 0.5) will reconstruct any model list
    // it needs from hydrationState.documents.

    return new Response(
      stringifyWithBigInt({
        ok: true,
        models: [],
        // parsedModels intentionally absent — server cannot send Langium ASTs
        // (circular $container refs). Task 0.5 rebuilds this client-side from
        // hydrationState.documents if needed.
        deferredExports: deferredExportsList.map(({ filePath: entryFilePath, namespace, entries }) => ({
          filePath: entryFilePath,
          namespace,
          exports: entries
        })),
        errors,
        hydrationState: { documents: documentsForHydration },
        dependencyGraph
      }),
      {
        status: 200,
        headers: { 'Content-Type': 'application/json' }
      }
    );
  } catch (err) {
    return new Response(
      JSON.stringify({
        ok: false,
        error: err instanceof Error ? err.message : String(err)
      }),
      { status: 500, headers: { 'Content-Type': 'application/json' } }
    );
  }
};

/**
 * Hydrate user-authored .rune files into a Langium workspace: parse via the
 * grammar, build + link, then serialize each model into JSON for the
 * response's `hydrationState`. Returns the live LangiumDocument[] + services
 * so the caller can reuse them for the cross-namespace dep-graph pass
 * (which deserializes curated docs into the same workspace before walking).
 *
 * Lazy-imports `@rune-langium/core` so requests with no work (no user
 * files AND no curated bundles) don't pay the ~1.8 MB bundle init cost.
 *
 * Mutates the passed-in `errors`, `documentsForHydration`, and
 * `deferredExportsList` collections; returns the services + docs.
 */
async function hydrateUserWorkspace(
  files: ReadonlyArray<{ name: string; content: string }>,
  errors: Record<string, string[]>,
  documentsForHydration: Array<{
    uri: string;
    content: string;
    serializedModel: string;
    exports: Array<{ type: string; name: string; path: string }>;
  }>,
  deferredExportsList: Array<{ filePath: string; namespace: string; entries: Array<{ type: string; name: string }> }>
): Promise<WorkspaceContext> {
  const [{ createRuneDslServices }, { EmptyFileSystem }] = await Promise.all([
    import('@rune-langium/core'),
    import('langium')
  ]);
  const { RuneDsl, shared } = createRuneDslServices(EmptyFileSystem);
  const factory = shared.workspace.LangiumDocumentFactory;
  const builder = shared.workspace.DocumentBuilder;

  const docs = files.map((f) => factory.fromString(f.content, toRosettaUri(f.name)));
  await builder.build(docs, { validation: false });

  for (let i = 0; i < docs.length; i++) {
    const doc = docs[i];
    const filePath = files[i].name;
    const parseErrors = doc.parseResult.parserErrors.map((e) => e.message);
    if (parseErrors.length > 0) {
      errors[filePath] = parseErrors;
    }
    const model = doc.parseResult.value as RosettaModel | undefined;
    if (!model) continue;

    // Copy CST source text into `$cstText` on Function/Data/Choice
    // condition + expression nodes BEFORE serializing. The visual editor
    // reads `$cstText` to render expression cells (functions with
    // conditions, function bodies, function expressions). Without this
    // pre-serialization step, the deserialized AST has no source text
    // — langium's `$cstNode` lives only on the live AST, not in the
    // serialized JSON — and the visual editor renders affected
    // expressions as blank even though the parse succeeded (Codex P2).
    //
    // `preserveCstText` is the shared @rune-langium/core helper, called on both the
    // browser worker and this server path so the routed parse output keeps the
    // expression CST text after the JSON round-trip (V7 — single source of truth).
    preserveCstText(model);

    // textRegions + refText preserve text-region offsets so language-
    // server features (e.g. go-to-definition, hover, code-action ranges)
    // can map AST nodes back to source spans after deserialization.
    // The BigInt replacer keeps large numeric literals JSON-safe — the
    // outer stringifyWithBigInt also handles them, but doing it inside
    // the langium serializer is more efficient (avoids one re-scan of
    // the embedded model JSON).
    const namespace = namespaceFromModelName(model.name) ?? '';
    const rawSerialized = serializeRuneModel(RuneDsl.serializer.JsonSerializer, model);
    const serializedModel = (() => {
      if (!namespace) return rawSerialized;
      const parsed = JSON.parse(rawSerialized) as Record<string, unknown>;
      const elements = parsed['elements'];
      if (Array.isArray(elements)) {
        for (const el of elements) {
          if (el && typeof el === 'object') (el as Record<string, unknown>)['$namespace'] = namespace;
        }
      }
      return JSON.stringify(parsed, runeBigIntReplacer);
    })();

    const exports: Array<{ type: string; name: string; path: string }> = [];
    if (namespace) {
      for (const elem of model.elements) {
        const e = elem as { $type: string; name?: string };
        if (e.name) {
          exports.push({ type: e.$type, name: e.name, path: qualifiedExportPath(namespace, e.name) });
        }
      }
    }

    documentsForHydration.push({
      uri: filePath,
      content: files[i].content,
      serializedModel,
      exports
    });

    if (namespace) {
      // Emit ONE entry per file so the studio's nodeIdToFilePath builder
      // can route each name to the file that declares it. See the comment
      // in handlePost where deferredExportsList is initialized.
      deferredExportsList.push({
        filePath,
        namespace,
        entries: exports.map((e) => ({ type: e.type, name: e.name }))
      });
    }
  }

  return { shared, RuneDsl, userDocs: docs };
}

/**
 * Extract the curated doc's namespace from its serialized model and append
 * a per-FILE entry to the deferredExports list. Mutates the passed list in
 * place to match the same shape the in-browser parser-worker produces
 * (apps/studio/src/workers/parser-worker.ts:handleParseWorkspace emits one
 * entry per file, not per namespace).
 *
 * Why per-file and not per-namespace: a single namespace (e.g.
 * `cdm.base.datetime`) can be split across multiple `.rosetta` files
 * (`-type.rosetta`, `-enum.rosetta`, `-func.rosetta`). The earlier
 * per-namespace collapse would assign ALL of that namespace's exports to
 * whichever file was iterated first, so the studio's nodeIdToFilePath
 * map (EditorPage.tsx) would route every linkDocument call to the wrong
 * file. Cross-file linking then never fires for the file that actually
 * declares the clicked type, and curated nodes appear bodiless because
 * their AST never gets hydrated.
 *
 * Namespace comes from the top-level `name` field of the Langium-serialized
 * RosettaModel. We slice off the model preamble and run a small regex
 * rather than JSON.parse the whole body — the model bodies are large
 * (~kilobytes each) but `name` always appears within the first ~256 bytes.
 */
function mergeCuratedDocIntoDeferredExports(
  doc: { uri: string; serializedModel: string; exports: Array<{ type: string; name: string; path: string }> },
  deferredExportsList: Array<{ filePath: string; namespace: string; entries: Array<{ type: string; name: string }> }>
): void {
  const preamble = doc.serializedModel.slice(0, 256);
  const nameMatch = /"name"\s*:\s*"([^"]+)"/.exec(preamble);
  if (!nameMatch) return;
  const namespace = nameMatch[1].replace(/^"|"$/g, '');
  if (!namespace) return;

  deferredExportsList.push({
    filePath: doc.uri,
    namespace,
    entries: doc.exports.map((e) => ({ type: e.type, name: e.name }))
  });
}

/**
 * Envelope uses the canonical bigint policy (runeBigIntReplacer -> Number) so wire bytes
 * agree across all serialize paths (V8).
 */
function stringifyWithBigInt(value: unknown): string {
  return JSON.stringify(value, runeBigIntReplacer);
}

/**
 * Seed namespaces for the curated closure = the namespaces the user files
 * import. Read from the already-parsed user models (no link needed).
 * Exported for unit testing.
 */
export function collectUserSeedNamespaces(userDocs: ReadonlyArray<{ parseResult?: { value?: unknown } }>): Set<string> {
  const seeds = new Set<string>();
  for (const doc of userDocs) {
    const model = doc.parseResult?.value as { imports?: Array<{ importedNamespace?: unknown }> } | undefined;
    if (!model || !Array.isArray(model.imports)) continue;
    for (const imp of model.imports) {
      if (typeof imp.importedNamespace === 'string' && imp.importedNamespace.length > 0) {
        seeds.add(imp.importedNamespace);
      }
    }
  }
  return seeds;
}

