// SPDX-License-Identifier: MIT
// Generated by @rune-langium/codegen — do not edit
// Source namespace: test.rules

// --- rune-codegen runtime helpers (inlined) ---
const runeCheckOneOf = (values: (unknown | undefined | null)[]): boolean =>
  values.filter((v) => v !== undefined && v !== null).length === 1;

const runeCount = (arr: unknown[] | undefined | null): number => arr?.length ?? 0;

const runeAttrExists = (v: unknown): boolean =>
  v !== undefined && v !== null && !(Array.isArray(v) && v.length === 0);
// --- end runtime helpers ---

export interface AccountShape {
  balance: number;
  status: string;
  tier: string;
}

export class Account implements AccountShape {
  balance: number;
  status: string;
  tier: string;

  constructor(data: AccountShape) {
    this.balance = data.balance as typeof this.balance;
    this.status = data.status as typeof this.status;
    this.tier = data.tier as typeof this.tier;
  }

  static from(json: unknown): Account {
    if (!isAccount(json)) {
      throw new TypeError('not a Account: ' + JSON.stringify(json).slice(0, 100));
    }
    return new Account(json as AccountShape);
  }
}

export function isAccount(x: unknown): x is Account {
  if (typeof x !== 'object' || x === null) return false;
  if (typeof (x as Record<string, unknown>).balance !== 'number') return false;
  if (typeof (x as Record<string, unknown>).status !== 'string') return false;
  if (typeof (x as Record<string, unknown>).tier !== 'string') return false;
  return true;
}

export function validateIsActive(account: AccountShape): boolean {
  return Account.Account?.balance > 0;
}

export function validateIsPremium(account: AccountShape): boolean {
  return Account.Account?.tier === 'premium';
}
// (functions emitted by Phase 8b appear below this line)
