// SPDX-License-Identifier: MIT
// Generated by @rune-langium/codegen — do not edit
// Source namespace: test.rules

import { z } from 'zod';

// --- rune-codegen runtime helpers (inlined) ---
const runeCheckOneOf = (values: (unknown | undefined | null)[]): boolean =>
  values.filter((v) => v !== undefined && v !== null).length === 1;

const runeCount = (arr: unknown[] | undefined | null): number => arr?.length ?? 0;

const runeAttrExists = (v: unknown): boolean =>
  v !== undefined && v !== null && !(Array.isArray(v) && v.length === 0);
// --- end runtime helpers ---

export const AccountSchema = z.object({
  balance: z.number(),
  status: z.string(),
  tier: z.string()
});
export type Account = z.infer<typeof AccountSchema>;


export const validateIsActive = AccountSchema.refine(
  (data) => data.Account?.balance > 0,
  'IsActive'
);

export const validateIsPremium = AccountSchema.refine(
  (data) => data.Account?.tier === 'premium',
  'IsPremium'
);

export const runeReportRules = {
  'IsActive': { kind: 'eligibility' as const, inputType: 'Account' },
  'IsPremium': { kind: 'eligibility' as const, inputType: 'Account' },
} as const;
