// SPDX-License-Identifier: MIT
// Copyright (c) 2026 Pradeep Mouli

/**
 * Pure, AST-free dialect rendering for the SQL DDL emitter. One `Dialect`
 * object knows how a given database renders the small set of primitives the
 * emitter needs: identifier quoting, builtin → column type, the surrogate
 * primary-key clause, and the foreign-key column type (must match the PK type).
 */
export type SqlDialectName = 'postgres' | 'sqlserver';

export interface Dialect {
  readonly name: SqlDialectName;
  /** node-sql-parser database key for test validation. */
  readonly parserDatabase: 'postgresql' | 'transactsql';
  /** Max identifier length the engine allows (Postgres truncates at 63; SQL Server errors past 128). */
  readonly maxIdentifierLength: number;
  quote(identifier: string): string;
  columnType(builtinName: string): string;
  /** True if `name` is a known Rune builtin (vs. an unresolved type that columnType maps to TEXT by fallback). */
  isKnownBuiltin(name: string): boolean;
  /** The surrogate PK column definition, e.g. `"id" BIGINT ... PRIMARY KEY`. */
  pkColumn(name: string): string;
  /** The column type used for FK columns — must equal the referenced PK's type. */
  fkColumnType(): string;
}

// Rune builtin basic/record/typeAlias names → dialect column type.
const POSTGRES_TYPES: Record<string, string> = {
  string: 'TEXT',
  pattern: 'TEXT',
  boolean: 'BOOLEAN',
  number: 'NUMERIC',
  int: 'INTEGER',
  date: 'DATE',
  dateTime: 'TIMESTAMP',
  zonedDateTime: 'TIMESTAMPTZ',
  time: 'TIME',
  productType: 'TEXT',
  eventType: 'TEXT',
  calculation: 'TEXT'
};
const SQLSERVER_TYPES: Record<string, string> = {
  string: 'NVARCHAR(MAX)',
  pattern: 'NVARCHAR(MAX)',
  boolean: 'BIT',
  number: 'DECIMAL(38,10)',
  int: 'INT',
  date: 'DATE',
  dateTime: 'DATETIME2',
  zonedDateTime: 'DATETIMEOFFSET',
  time: 'TIME',
  productType: 'NVARCHAR(MAX)',
  eventType: 'NVARCHAR(MAX)',
  calculation: 'NVARCHAR(MAX)'
};

export function dialectFor(name: SqlDialectName): Dialect {
  if (name === 'sqlserver') {
    return {
      name,
      parserDatabase: 'transactsql',
      maxIdentifierLength: 128,
      quote: (id) => `[${id}]`,
      columnType: (b) => SQLSERVER_TYPES[b] ?? 'NVARCHAR(MAX)',
      isKnownBuiltin: (b) => b in SQLSERVER_TYPES,
      pkColumn: (n) => `[${n}] BIGINT IDENTITY(1,1) PRIMARY KEY`,
      fkColumnType: () => 'BIGINT'
    };
  }
  return {
    name: 'postgres',
    parserDatabase: 'postgresql',
    maxIdentifierLength: 63,
    quote: (id) => `"${id}"`,
    columnType: (b) => POSTGRES_TYPES[b] ?? 'TEXT',
    isKnownBuiltin: (b) => b in POSTGRES_TYPES,
    // BY DEFAULT (not ALWAYS) — allows explicit id insertion for migrations/seeds,
    // and is parseable by node-sql-parser (which rejects GENERATED ALWAYS).
    pkColumn: (n) => `"${n}" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY`,
    fkColumnType: () => 'BIGINT'
  };
}
