// SPDX-License-Identifier: MIT
// Copyright (c) 2026 Pradeep Mouli

/**
 * TypeScript `LanguageProfile` — 019 Phase 0.5.3.
 *
 * Mirrors `zodProfile` in structure: per-namespace emitter +
 * suppressBoilerplate-aware header + runtime sidecar + barrel module.
 * TypeScript has the same shared runtime helpers as Zod (used by
 * generated funcs), so the sidecar pattern applies here too.
 */

import { stripBundledImports } from './bundle-imports.js';
import { metadataRuntimeSource, runeFuncDataSource } from '../expr/metadata-runtime.js';
import type { GeneratorOutput } from '../types.js';
import type { LanguageProfile } from './language-profile.js';
import { RUNTIME_HELPER_SOURCE, RUNTIME_SIDECAR_HELPER_LINES, RUNE_HELPER_NAMES } from '../helpers.js';
import { CallableNames } from './callable-names.js';
import type { NamespaceRegistry } from './namespace-registry.js';

export const TS_LIBRARY_RUNTIME_SOURCE = `function isLeapYear(year: number): boolean {
  return (year % 4 === 0 && year % 100 !== 0) || year % 400 === 0;
}`;

const RUNTIME_SIDECAR_SOURCE = [
  `// SPDX-License-Identifier: MIT`,
  `// Generated by @rune-langium/codegen — do not edit`,
  `// Shared runtime helpers + builtin library-function implementations,`,
  `// imported by per-namespace .ts files in a 'barrel'/'single-file' bundle.`,
  `// Note: record types use Temporal.* — requires a polyfill or 'lib: esnext'.`,
  ``,
  ...RUNTIME_SIDECAR_HELPER_LINES,
  metadataRuntimeSource(true, true),
  ``,
  `export ${TS_LIBRARY_RUNTIME_SOURCE}`,
  ``
].join('\n');

/**
 * Relative path used as `importFrom` for builtin library functions that
 * resolve to the TS runtime sidecar (e.g. `IsLeapYear` → `isLeapYear`).
 * The sidecar file is `runtime.ts`; consumers import the compiled
 * `./runtime.js` (ESM `.js` extension at runtime) — mirrors how Zod's
 * per-namespace files import from `./runtime.zod.js`.
 */
export const TS_RUNTIME_SIDECAR_PATH = './runtime.js';

/**
 * Build the barrel `index.ts` content. `export * from './<ns>.js'`
 * per namespace re-exports every interface, type alias, and func.
 */
function makeBarrelContent(perNs: ReadonlyArray<GeneratorOutput>, registry: NamespaceRegistry): string {
  const names = new CallableNames(registry);
  const lines = [
    `// SPDX-License-Identifier: MIT`,
    `// Generated by @rune-langium/codegen — do not edit`,
    `// Barrel re-export of every namespace module in this bundle.`,
    ``
  ];
  for (const out of perNs) {
    const modulePath = `./${out.relativePath.replace(/\.ts$/, '.js')}`;
    const namespace = out.relativePath.replace(/\.ts$/, '').replace(/\//g, '.');
    const exports = new Map<string, boolean>();
    for (const match of out.content.matchAll(/^export (type|interface|class|function|const) ([\w$]+)/gm)) {
      const name = match[2]!;
      exports.set(name, exports.get(name) === true || (match[1] !== 'type' && match[1] !== 'interface'));
    }
    const bindings = [...exports].map(([name, hasValue]) => {
      const bundled = names.bundled(namespace, name);
      return `${hasValue ? '' : 'type '}${bundled === name ? name : `${name} as ${bundled}`}`;
    });
    lines.push(
      bindings.some((binding) => binding.includes(' as '))
        ? `export { ${bindings.join(', ')} } from '${modulePath}';`
        : `export * from '${modulePath}';`
    );
  }
  lines.push('');
  return lines.join('\n');
}

/**
 * Build the single-file `model.ts` by concatenating per-namespace
 * contents under a unified header + one inlined helpers block. Strips
 * each per-namespace's now-redundant header so the result has one
 * canonical preamble.
 */
function makeSingleFileContent(perNs: ReadonlyArray<GeneratorOutput>): string {
  const namespaces = perNs.map((o) => o.relativePath.replace(/\.ts$/, '').replace(/\//g, '.')).join(', ');
  const sections: string[] = [
    `// SPDX-License-Identifier: MIT`,
    `// Generated by @rune-langium/codegen — do not edit`,
    `// Single-file bundle for namespaces: ${namespaces}`,
    ``,
    RUNTIME_HELPER_SOURCE,
    ...(perNs.some((output) => output.content.includes('isLeapYear')) ? [TS_LIBRARY_RUNTIME_SOURCE] : []),
    ...(perNs.some((output) => output.content.includes('runeWithMeta')) ? [metadataRuntimeSource(true)] : []),
    ...(perNs.some((output) => output.content.includes('type RuneFuncData<')) ? [runeFuncDataSource()] : []),
    ``
  ];
  for (const out of perNs) {
    const body = stripBundledImports(
      stripPerNamespaceFuncDataType(stripPerNamespaceHeader(out.content)),
      out.relativePath,
      perNs.map((output) => output.relativePath),
      '.ts'
    );
    if (body.length > 0) {
      sections.push(`// --- namespace: ${out.relativePath} ---`);
      sections.push(body);
    }
  }
  return sections.join('\n');
}

function stripPerNamespaceFuncDataType(content: string): string {
  const marker = 'type RuneFuncData<T> = T extends readonly (infer I)[]';
  const start = content.indexOf(marker);
  if (start < 0) return content;
  const end = content.indexOf('\n\n', start);
  return end < 0 ? content.slice(0, start).trimEnd() : `${content.slice(0, start)}${content.slice(end + 2)}`.trim();
}

/**
 * Strip the per-namespace header from content produced with
 * `suppressBoilerplate: true`. The header shape is: SPDX + generated
 * + source-namespace + blank + `import { ... } from './runtime.js'` +
 * blank. The body begins after that.
 */
function stripPerNamespaceHeader(content: string): string {
  const lines = content.split('\n');
  let bodyStart = 0;
  for (let i = 0; i < lines.length; i++) {
    if (lines[i]?.startsWith(`import { ${RUNE_HELPER_NAMES[0]},`)) {
      bodyStart = i + 1;
      if (bodyStart < lines.length && lines[bodyStart] === '') bodyStart += 1;
      break;
    }
  }
  if (bodyStart === 0) return content;
  return lines.slice(bodyStart).join('\n').trimEnd();
}

export const typescriptProfile: LanguageProfile<'typescript'> = {
  target: 'typescript',
  extension: '.ts',

  // Builtin type maps (§4a of the builtin-type-mapping design spec).
  // Note: record types use Temporal.* — requires a polyfill or 'lib: esnext'.
  basicTypeMap: {
    boolean: 'boolean',
    number: 'number',
    string: 'string',
    time: 'Temporal.PlainTime',
    pattern: 'string'
  },
  recordTypeMap: {
    date: 'Temporal.PlainDate',
    dateTime: 'Temporal.PlainDateTime',
    zonedDateTime: 'Temporal.ZonedDateTime'
  },
  typeAliasMap: {
    int: 'number',
    productType: 'string',
    eventType: 'string',
    calculation: 'string'
  },
  libraryFuncMap: {
    Min: { expr: 'Math.min' },
    Max: { expr: 'Math.max' },
    IsLeapYear: { expr: 'isLeapYear', importFrom: TS_RUNTIME_SIDECAR_PATH },
    DateRanges: null,
    Adjust: null,
    Within: null
  },
  makeBarrel(perNs, registry) {
    return {
      relativePath: 'index.ts',
      content: makeBarrelContent(perNs, registry),
      sourceMap: [],
      diagnostics: [],
      funcs: []
    };
  },
  concatenate(perNs) {
    return {
      relativePath: 'model.ts',
      content: makeSingleFileContent(perNs),
      sourceMap: [],
      diagnostics: [],
      funcs: []
    };
  },
  makeSharedArtifacts() {
    return [
      {
        relativePath: 'runtime.ts',
        content: RUNTIME_SIDECAR_SOURCE,
        sourceMap: [],
        diagnostics: [],
        funcs: []
      }
    ];
  },
  singleFileLimits: {
    maxNamespaces: 50,
    maxBytes: 1_048_576
  }
};
