// SPDX-License-Identifier: MIT
// Copyright (c) 2026 Pradeep Mouli

/**
 * TypeScript `LanguageProfile` — 019 Phase 0.5.3.
 *
 * Mirrors `zodProfile` in structure: per-namespace emitter +
 * suppressBoilerplate-aware header + runtime sidecar + barrel module.
 * TypeScript has the same shared runtime helpers as Zod (used by
 * generated funcs), so the sidecar pattern applies here too.
 */

import type { GeneratorOutput } from '../types.js';
import type { LanguageProfile } from './language-profile.js';
import { RUNTIME_HELPER_SOURCE } from '../helpers.js';

const RUNTIME_SIDECAR_SOURCE = [
  `// SPDX-License-Identifier: MIT`,
  `// Generated by @rune-langium/codegen — do not edit`,
  `// Shared runtime helpers — imported by every per-namespace .ts file`,
  `// in a 'barrel' or 'single-file' TypeScript bundle.`,
  ``,
  `export const runeCheckOneOf = (values: (unknown | undefined | null)[]): boolean =>`,
  `  values.filter((v) => v !== undefined && v !== null).length === 1;`,
  ``,
  `export const runeCount = (arr: unknown[] | undefined | null): number => arr?.length ?? 0;`,
  ``,
  `export const runeAttrExists = (v: unknown): boolean =>`,
  `  v !== undefined && v !== null && !(Array.isArray(v) && v.length === 0);`,
  ``
].join('\n');

/**
 * Build the barrel `index.ts` content. `export * from './<ns>.js'`
 * per namespace re-exports every interface, type alias, and func.
 */
function makeBarrelContent(perNs: ReadonlyArray<GeneratorOutput>): string {
  const lines = [
    `// SPDX-License-Identifier: MIT`,
    `// Generated by @rune-langium/codegen — do not edit`,
    `// Barrel re-export of every namespace module in this bundle.`,
    ``
  ];
  for (const out of perNs) {
    const modulePath = `./${out.relativePath.replace(/\.ts$/, '.js')}`;
    lines.push(`export * from '${modulePath}';`);
  }
  lines.push('');
  return lines.join('\n');
}

/**
 * Build the single-file `model.ts` by concatenating per-namespace
 * contents under a unified header + one inlined helpers block. Strips
 * each per-namespace's now-redundant header so the result has one
 * canonical preamble.
 */
function makeSingleFileContent(perNs: ReadonlyArray<GeneratorOutput>): string {
  const namespaces = perNs.map((o) => o.relativePath.replace(/\.ts$/, '').replace(/\//g, '.')).join(', ');
  const sections: string[] = [
    `// SPDX-License-Identifier: MIT`,
    `// Generated by @rune-langium/codegen — do not edit`,
    `// Single-file bundle for namespaces: ${namespaces}`,
    ``,
    RUNTIME_HELPER_SOURCE,
    ``
  ];
  for (const out of perNs) {
    const body = stripPerNamespaceHeader(out.content);
    if (body.length > 0) {
      sections.push(`// --- namespace: ${out.relativePath} ---`);
      sections.push(body);
    }
  }
  return sections.join('\n');
}

/**
 * Strip the per-namespace header from content produced with
 * `suppressBoilerplate: true`. The header shape is: SPDX + generated
 * + source-namespace + blank + `import { ... } from './runtime.js'` +
 * blank. The body begins after that.
 */
function stripPerNamespaceHeader(content: string): string {
  const lines = content.split('\n');
  let bodyStart = 0;
  for (let i = 0; i < lines.length; i++) {
    if (lines[i]?.startsWith(`import { runeCheckOneOf,`)) {
      bodyStart = i + 1;
      if (bodyStart < lines.length && lines[bodyStart] === '') bodyStart += 1;
      break;
    }
  }
  if (bodyStart === 0) return content;
  return lines.slice(bodyStart).join('\n').trimEnd();
}

export const typescriptProfile: LanguageProfile<'typescript'> = {
  target: 'typescript',
  extension: '.ts',
  makeBarrel(perNs) {
    return {
      relativePath: 'index.ts',
      content: makeBarrelContent(perNs),
      sourceMap: [],
      diagnostics: [],
      funcs: []
    };
  },
  concatenate(perNs) {
    return {
      relativePath: 'model.ts',
      content: makeSingleFileContent(perNs),
      sourceMap: [],
      diagnostics: [],
      funcs: []
    };
  },
  makeSharedArtifacts() {
    return [
      {
        relativePath: 'runtime.ts',
        content: RUNTIME_SIDECAR_SOURCE,
        sourceMap: [],
        diagnostics: [],
        funcs: []
      }
    ];
  },
  singleFileLimits: {
    maxNamespaces: 50,
    maxBytes: 1_048_576
  }
};
