// SPDX-License-Identifier: MIT
// Copyright (c) 2026 Pradeep Mouli

/**
 * Zod `LanguageProfile` — 019 Phase 0.5.2.
 *
 * Combined with `ZodNamespaceEmitter` (configured with
 * `suppressBoilerplate: true`) and `GenericModelEmitter`, this profile
 * produces the bundled whole-model layouts: `'barrel'` (default) and
 * `'single-file'`.
 */

import type { GeneratorOutput } from '../types.js';
import type { LanguageProfile } from './language-profile.js';
import { RUNTIME_HELPER_SOURCE } from '../helpers.js';

/**
 * The shared `runtime.zod.ts` sidecar content. Mirrors
 * `RUNTIME_HELPER_SOURCE` but with `export const` declarations so the
 * helpers are importable from each per-namespace file via the import
 * line `ZodNamespaceEmitter` emits when `suppressBoilerplate: true`.
 */
const RUNTIME_SIDECAR_SOURCE = [
  `// SPDX-License-Identifier: MIT`,
  `// Generated by @rune-langium/codegen — do not edit`,
  `// Shared runtime helpers — imported by every per-namespace .zod.ts`,
  `// in a 'barrel' or 'single-file' Zod bundle.`,
  ``,
  `export const runeCheckOneOf = (values: (unknown | undefined | null)[]): boolean =>`,
  `  values.filter((v) => v !== undefined && v !== null).length === 1;`,
  ``,
  `export const runeCount = (arr: unknown[] | undefined | null): number => arr?.length ?? 0;`,
  ``,
  `export const runeAttrExists = (v: unknown): boolean =>`,
  `  v !== undefined && v !== null && !(Array.isArray(v) && v.length === 0);`,
  ``
].join('\n');

/**
 * Build the barrel `index.zod.ts` content. Re-exports every per-namespace
 * schema module so consumers can `import { TradeSchema } from
 * './my-zod-bundle'` against the bundle as a whole.
 *
 * Files are listed in `perNs` order, which `GenericModelEmitter` sorts
 * by `relativePath` — deterministic across runs.
 */
function makeBarrelContent(perNs: ReadonlyArray<GeneratorOutput>): string {
  const lines = [
    `// SPDX-License-Identifier: MIT`,
    `// Generated by @rune-langium/codegen — do not edit`,
    `// Barrel re-export of every namespace schema in this bundle.`,
    ``
  ];
  for (const out of perNs) {
    // Drop the leading directory portion of the relativePath when
    // building the `from '...'` specifier — TypeScript module resolution
    // wants a path relative to this barrel, which lives at the same
    // level as the per-namespace files.
    const modulePath = `./${out.relativePath.replace(/\.ts$/, '.js')}`;
    lines.push(`export * from '${modulePath}';`);
  }
  lines.push('');
  return lines.join('\n');
}

/**
 * Build the single-file `model.zod.ts` by concatenating the
 * per-namespace contents under a unified header + one inlined runtime
 * helpers block. The per-namespace files have `suppressBoilerplate:
 * true` so their own headers reference `./runtime.zod.js` — when
 * concatenating, we strip each per-namespace header (everything up to
 * and including the runtime import line) so the result has one
 * canonical preamble.
 */
function makeSingleFileContent(perNs: ReadonlyArray<GeneratorOutput>): string {
  const namespaces = perNs.map((o) => o.relativePath.replace(/\.zod\.ts$/, '').replace(/\//g, '.')).join(', ');
  const sections: string[] = [
    `// SPDX-License-Identifier: MIT`,
    `// Generated by @rune-langium/codegen — do not edit`,
    `// Single-file bundle for namespaces: ${namespaces}`,
    ``,
    `import { z } from 'zod';`,
    ``,
    RUNTIME_HELPER_SOURCE,
    ``
  ];
  for (const out of perNs) {
    const body = stripPerNamespaceHeader(out.content);
    if (body.length > 0) {
      sections.push(`// --- namespace: ${out.relativePath} ---`);
      sections.push(body);
    }
  }
  return sections.join('\n');
}

/**
 * Remove the per-namespace file header from `content` produced by
 * `ZodNamespaceEmitter` with `suppressBoilerplate: true`. The header
 * shape is fixed: SPDX line + generated comment + source-namespace
 * line + blank + `import { z }` + `import { ... } from './runtime.zod.js'`
 * + blank. After that the body begins.
 *
 * Returns the body, trimming any trailing blank line. If the expected
 * header pattern isn't found (defensive — should never happen with the
 * current emitter), returns the content unchanged so concatenation
 * still produces something usable.
 */
function stripPerNamespaceHeader(content: string): string {
  const lines = content.split('\n');
  let bodyStart = 0;
  for (let i = 0; i < lines.length; i++) {
    if (lines[i]?.startsWith(`import { runeCheckOneOf,`)) {
      bodyStart = i + 1;
      // Skip the trailing blank line after the import block.
      if (bodyStart < lines.length && lines[bodyStart] === '') bodyStart += 1;
      break;
    }
  }
  if (bodyStart === 0) return content; // header not found — return as-is
  return lines.slice(bodyStart).join('\n').trimEnd();
}

export const zodProfile: LanguageProfile<'zod'> = {
  target: 'zod',
  extension: '.zod.ts',
  makeBarrel(perNs) {
    return {
      relativePath: 'index.zod.ts',
      content: makeBarrelContent(perNs),
      sourceMap: [],
      diagnostics: [],
      funcs: []
    };
  },
  concatenate(perNs) {
    return {
      relativePath: 'model.zod.ts',
      content: makeSingleFileContent(perNs),
      sourceMap: [],
      diagnostics: [],
      funcs: []
    };
  },
  makeSharedArtifacts() {
    return [
      {
        relativePath: 'runtime.zod.ts',
        content: RUNTIME_SIDECAR_SOURCE,
        sourceMap: [],
        diagnostics: [],
        funcs: []
      }
    ];
  },
  // 019 spec §10.2 — CDM-scale models (~80 namespaces) exceed the
  // single-file practical threshold, so we error out before producing
  // an unwieldy artifact. Callers see a fatal `single-file-too-large`
  // diagnostic and pick `barrel` or `per-namespace` instead.
  singleFileLimits: {
    maxNamespaces: 50,
    maxBytes: 1_048_576
  }
};
