// SPDX-License-Identifier: MIT
// Generated by @rune-langium/codegen — do not edit
// Source namespace: test.cond.multi

import { z } from 'zod';

// --- rune-codegen runtime helpers (inlined) ---
const runeCheckOneOf = (values: (unknown | undefined | null)[]): boolean =>
  values.filter((v) => v !== undefined && v !== null).length === 1;

const runeCount = (arr: unknown[] | undefined | null): number => arr?.length ?? 0;

const runeAttrExists = (v: unknown): boolean =>
  v !== undefined && v !== null && !(Array.isArray(v) && v.length === 0);
// --- end runtime helpers ---

export const UnitTypeSchema = z
  .object({
    a: z.string().optional(),
    b: z.string().optional(),
    c: z.string().optional()
  })
  .superRefine((data, ctx) => {
    if (!runeAttrExists(data.a)) {
      ctx.addIssue({
        code: 'custom',
        message: 'AExists: a must be present in UnitType',
        path: ['AExists']
      });
    }
    if (runeAttrExists(data.b)) {
      ctx.addIssue({
        code: 'custom',
        message: 'BAbsent: b must be absent in UnitType',
        path: ['BAbsent']
      });
    }
    if (!runeCheckOneOf([data.a, data.c])) {
      ctx.addIssue({
        code: 'custom',
        message: 'OneOfAC: exactly one of [a, c] must be present in UnitType',
        path: ['OneOfAC']
      });
    }
  });
export type UnitType = z.infer<typeof UnitTypeSchema>;
