// SPDX-License-Identifier: MIT
// Generated by @rune-langium/codegen — do not edit
// Source namespace: test.cond.aggregations

import { z } from 'zod';

// --- rune-codegen runtime helpers (inlined) ---
const runeCheckOneOf = (values: (unknown | undefined | null)[]): boolean =>
  values.filter((v) => v !== undefined && v !== null).length === 1;

const runeCount = (arr: unknown[] | undefined | null): number => arr?.length ?? 0;

const runeAttrExists = (v: unknown): boolean =>
  v !== undefined && v !== null && !(Array.isArray(v) && v.length === 0);
// --- end runtime helpers ---

export const AggCheckSchema = z
  .object({
    values: z.array(z.number().int())
  })
  .superRefine((data, ctx) => {
    if (!(runeCount(data.values) > 0)) {
      ctx.addIssue({
        code: 'custom',
        message: 'CountPositive: condition failed in AggCheck',
        path: ['CountPositive']
      });
    }
    if (!runeAttrExists((data.values ?? [])[0])) {
      ctx.addIssue({
        code: 'custom',
        message: 'FirstExists: condition failed in AggCheck',
        path: ['FirstExists']
      });
    }
  });
export type AggCheck = z.infer<typeof AggCheckSchema>;
