// SPDX-License-Identifier: MIT
// Generated by @rune-langium/codegen — do not edit
// Source namespace: test.cond.choice

import { z } from 'zod';

// --- rune-codegen runtime helpers (inlined) ---

import { Temporal } from '@js-temporal/polyfill';
const runeParseZonedDateTime = (value: unknown): Temporal.ZonedDateTime => {
  const text = String(value);
  const offset = text.match(/(Z|[+-]\d{2}:\d{2})$/)?.[1];
  return Temporal.ZonedDateTime.from(offset ? text + '[' + (offset === 'Z' ? 'UTC' : offset) + ']' : text);
};
const runeDateField = <K extends 'year' | 'month' | 'day' | 'date' | 'time' | 'timezone'>(value: unknown, kind: 'date' | 'dateTime' | 'zonedDateTime', field: K): (K extends 'year' | 'month' | 'day' ? number : string) | undefined => {
  if (value == null) return undefined;
  const parsed = kind === 'date' ? Temporal.PlainDate.from(String(value)) : kind === 'dateTime' ? Temporal.PlainDateTime.from(String(value)) : runeParseZonedDateTime(value);
  const result = field === 'date' && 'toPlainDate' in parsed ? parsed.toPlainDate().toString()
    : field === 'time' && 'toPlainTime' in parsed ? parsed.toPlainTime().toString()
    : field === 'timezone' && 'timeZoneId' in parsed ? parsed.timeZoneId
    : field === 'year' ? parsed.year : field === 'month' ? parsed.month : field === 'day' ? parsed.day : undefined;
  return result as (K extends 'year' | 'month' | 'day' ? number : string) | undefined;
};
const runeDateConstructTemporal = <K extends 'date' | 'dateTime' | 'zonedDateTime'>(kind: K, fields: { year?: number; month?: number; day?: number; date?: Temporal.PlainDate; time?: Temporal.PlainTime; timezone?: string }): (K extends 'date' ? Temporal.PlainDate : K extends 'dateTime' ? Temporal.PlainDateTime : Temporal.ZonedDateTime) | undefined => {
  const construct = () => {
    if (kind === 'date') {
      if (fields.year == null || fields.month == null || fields.day == null) return undefined;
      return Temporal.PlainDate.from({ year: fields.year, month: fields.month, day: fields.day }, { overflow: 'reject' });
    }
    if (fields.date == null || fields.time == null) return undefined;
    const dateTime = fields.date.toPlainDateTime(fields.time);
    if (kind === 'dateTime') return dateTime;
    if (fields.timezone == null) return undefined;
    return dateTime.toZonedDateTime(fields.timezone === 'Z' ? 'UTC' : fields.timezone);
  };
  return construct() as (K extends 'date' ? Temporal.PlainDate : K extends 'dateTime' ? Temporal.PlainDateTime : Temporal.ZonedDateTime) | undefined;
};
const runeDateConstruct = (kind: 'date' | 'dateTime' | 'zonedDateTime', fields: { year?: number; month?: number; day?: number; date?: string; time?: string; timezone?: string }): string | undefined => runeDateConstructTemporal(kind, {
  ...fields,
  date: fields.date == null ? undefined : Temporal.PlainDate.from(fields.date),
  time: fields.time == null ? undefined : Temporal.PlainTime.from(fields.time)
})?.toString();

type RuneFuncData<T> = T extends readonly (infer I)[]
  ? RuneFuncData<I>[]
  : T extends { readonly [Symbol.toStringTag]: `Temporal.${string}` }
    ? T
    : T extends (...args: never[]) => unknown
      ? never
      : T extends object
        ? { [K in keyof T as T[K] extends (...args: never[]) => unknown ? never : K]: RuneFuncData<T[K]> }
        : T;
const runeToFuncData = <T>(input: T): RuneFuncData<T> => {
  const seen = new WeakMap<object, unknown>();
  const convert = (value: unknown): unknown => {
    if (value == null || typeof value !== 'object') return value;
    if (/^\[object Temporal\./.test(Object.prototype.toString.call(value))) return value;
    if (seen.has(value)) return seen.get(value);
    if (Array.isArray(value)) {
      const result: unknown[] = [];
      seen.set(value, result);
      for (const item of value) result.push(convert(item));
      return result;
    }
    const result: Record<string, unknown> = {};
    seen.set(value, result);
    for (const [key, item] of Object.entries(value)) if (typeof item !== 'function') Object.defineProperty(result, key, { value: convert(item), enumerable: true, writable: true, configurable: true });
    return result;
  };
  return convert(input) as RuneFuncData<T>;
};

type RuneOperand<T> = T extends readonly (infer I)[] ? NonNullable<I> : NonNullable<T>;
const runeBinary = <L, R, V>(left: L, right: R, operate: (a: RuneOperand<L>, b: RuneOperand<R>) => V): L extends readonly unknown[] | null | undefined ? V | undefined : R extends readonly unknown[] | null | undefined ? V | undefined : V => {
  const l = runeList(left).filter((value) => value != null);
  const r = runeList(right).filter((value) => value != null);
  return (l.length === 1 && r.length === 1 ? operate(l[0] as RuneOperand<L>, r[0] as RuneOperand<R>) : undefined) as L extends readonly unknown[] | null | undefined ? V | undefined : R extends readonly unknown[] | null | undefined ? V | undefined : V;
};
const runeCompare = <A, B>(left: A, right: B, compare: (a: RuneOperand<A>, b: RuneOperand<B>) => boolean, quantifier: 'all' | 'any' = 'all'): boolean => {
  const l = runeList(left).filter((value) => value != null);
  const r = runeList(right).filter((value) => value != null);
  if (l.length === 0 || r.length === 0) return false;
  return quantifier === 'all' ? l.every((a) => r.every((b) => compare(a as RuneOperand<A>, b as RuneOperand<B>))) : l.some((a) => r.some((b) => compare(a as RuneOperand<A>, b as RuneOperand<B>)));
};
const runeOrder = <T>(left: T, right: T, compare: (a: NonNullable<T>, b: NonNullable<T>) => number, nullsLast = true): number => {
  if (left == null) return right == null ? 0 : nullsLast ? 1 : -1;
  if (right == null) return nullsLast ? -1 : 1;
  return compare(left, right);
};

const runeList = <T>(value: T): (T extends readonly (infer I)[] ? I : NonNullable<T>)[] => {
  if (value == null) return [];
  return (Array.isArray(value) ? value : [value]) as (T extends readonly (infer I)[] ? I : NonNullable<T>)[];
};
const runeSingle = <T>(value: T): T extends readonly (infer I)[] ? I | undefined : T extends null | undefined ? undefined : T => {
  const values = runeList(value);
  if (values.length > 1) throw new Error('Expected at most one value');
  return values[0] as T extends readonly (infer I)[] ? I | undefined : T extends null | undefined ? undefined : T;
};
const runeContains = (left: unknown, right: unknown): boolean => {
  const l = runeList(left), r = runeList(right);
  const keys = new Set(l.map(runeValueKey));
  return l.length > 0 && r.length > 0 && r.every((value) => keys.has(runeValueKey(value)));
};
const runeDisjoint = (left: unknown, right: unknown): boolean => {
  const keys = new Set(runeList(right).map(runeValueKey));
  return !runeList(left).some((value) => keys.has(runeValueKey(value)));
};
const runeDistinct = <T>(value: T, key: (item: T extends readonly (infer I)[] ? I : NonNullable<T>) => string = runeValueKey): (T extends readonly (infer I)[] ? I : NonNullable<T>)[] => {
  const seen = new Set<string>();
  return runeList(value).filter((item) => {
    const identity = key(item);
    if (seen.has(identity)) return false;
    seen.add(identity);
    return true;
  });
};

const runeCheckOneOf = (values: unknown[]): boolean =>
  values.filter((v) => v !== undefined && v !== null && !(Array.isArray(v) && v.length === 0)).length === 1;

const runeCount = (value: unknown): number => Array.isArray(value) ? value.length : value == null ? 0 : 1;

const runeAttrExists = <T>(v: T): v is NonNullable<T> & (T extends readonly (infer I)[] ? readonly [I, ...I[]] : unknown) =>
  v !== undefined && v !== null && !(Array.isArray(v) && v.length === 0);

const runeToDate = (v: unknown): string | undefined =>
  typeof v === 'string' && /^\d{4}-\d{2}-\d{2}$/.test(v) ? v : undefined;

const runeToTime = (v: unknown): string | undefined =>
  typeof v === 'string' && /^\d{2}:\d{2}:\d{2}(\.\d+)?$/.test(v) ? v : undefined;

const runeToDateTime = (v: unknown): string | undefined =>
  typeof v === 'string' && /^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(\.\d+)?$/.test(v) ? v : undefined;

const runeToZonedDateTime = (v: unknown): string | undefined =>
  typeof v === 'string' && /^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(\.\d+)?(Z|[+-]\d{2}:\d{2})(\[[^\]]+\])?$/.test(v) ? v : undefined;

const runeValueKey = (value: unknown): string => {
  if (value == null) return 'null';
  if (typeof value !== 'object') return typeof value + ':' + String(value);
  if (Array.isArray(value)) return 'array:' + JSON.stringify(value.map(runeValueKey));
  const tag = Object.prototype.toString.call(value);
  if (/^\[object Temporal\.(PlainDate|PlainTime|PlainDateTime|ZonedDateTime|Instant|PlainYearMonth|PlainMonthDay|Duration)\]$/.test(tag)) return tag + ':' + String(value);
  const fields = value as Record<string, unknown>;
  return 'object:' + JSON.stringify(Object.keys(fields).sort().filter((key) => fields[key] != null).map((key) => [key, runeValueKey(fields[key])]));
};
const rune = {
  equals: (left: unknown, right: unknown, quantifier?: 'all' | 'any', unequal = false): boolean => {
    if (quantifier == null) {
      const same = runeValueKey(left) === runeValueKey(right);
      return unequal ? !same : same;
    }
    const leftArray = Array.isArray(left), rightArray = Array.isArray(right);
    const l = leftArray ? left : left == null ? [] : [left];
    const r = rightArray ? right : right == null ? [] : [right];
    if (l.length === 0 || r.length === 0) {
      const same = leftArray === rightArray && l.length === r.length;
      return unequal ? !same : same;
    }
    const compare = (a: unknown, b: unknown) => unequal ? !rune.equals(a, b) : rune.equals(a, b);
    if (!leftArray) return quantifier === 'all' ? r.every((b) => compare(left, b)) : r.some((b) => compare(left, b));
    if (!rightArray) return quantifier === 'all' ? l.every((a) => compare(a, right)) : l.some((a) => compare(a, right));
    return quantifier === 'all'
      ? (unequal || l.length === r.length) && l.every((a, i) => i >= r.length ? unequal : compare(a, r[i]))
      : (unequal && l.length !== r.length) || l.some((a, i) => i < r.length && compare(a, r[i]));
  },
  list: runeList,
  single: runeSingle,
  contains: runeContains,
  disjoint: runeDisjoint,
  distinct: runeDistinct,
  binary: runeBinary,
  compare: runeCompare,
  order: runeOrder,
  parseZonedDateTime: runeParseZonedDateTime,
  dateField: runeDateField,
  dateConstruct: runeDateConstruct,
  dateConstructTemporal: runeDateConstructTemporal,
  toFuncData: runeToFuncData,
  checkOneOf: runeCheckOneOf,
  count: runeCount,
  exists: runeAttrExists,
  valueKey: runeValueKey,
  toDate: runeToDate,
  toTime: runeToTime,
  toDateTime: runeToDateTime,
  toZonedDateTime: runeToZonedDateTime
};

// --- end runtime helpers ---

const runeExtendChoice = <T extends z.ZodUnion<readonly z.ZodObject[]>>(choice: T, shape: z.ZodRawShape) =>
  z.union(choice.options.map((arm) => arm.extend(shape)));

export const UnitTypeSchema = z
  .object({
    a: z.string().optional(),
    b: z.string().optional(),
    c: z.string().optional()
  })
  .refine(
    (data) => rune.checkOneOf([data.a, data.b, data.c]),
    'Pick: exactly one of [a, b, c] must be present in UnitType'
  );
export type UnitType = z.infer<typeof UnitTypeSchema>;
