// SPDX-License-Identifier: MIT
// Generated by @rune-langium/codegen — do not edit
// Source namespace: test.cond.arithmetic

import { z } from 'zod';

// --- rune-codegen runtime helpers (inlined) ---
const runeCheckOneOf = (values: (unknown | undefined | null)[]): boolean =>
  values.filter((v) => v !== undefined && v !== null).length === 1;

const runeCount = (arr: unknown[] | undefined | null): number => arr?.length ?? 0;

const runeAttrExists = (v: unknown): boolean =>
  v !== undefined && v !== null && !(Array.isArray(v) && v.length === 0);

const runeToDate = (v: unknown): string | undefined =>
  typeof v === 'string' && /^\d{4}-\d{2}-\d{2}$/.test(v) ? v : undefined;

const runeToTime = (v: unknown): string | undefined =>
  typeof v === 'string' && /^\d{2}:\d{2}:\d{2}(\.\d+)?$/.test(v) ? v : undefined;

const runeToDateTime = (v: unknown): string | undefined =>
  typeof v === 'string' && /^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(\.\d+)?$/.test(v) ? v : undefined;

const runeToZonedDateTime = (v: unknown): string | undefined =>
  typeof v === 'string' && /^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(\.\d+)?(Z|[+-]\d{2}:\d{2})(\[[^\]]+\])?$/.test(v)
    ? v
    : undefined;
// --- end runtime helpers ---

const runeExtendChoice = <T extends z.ZodUnion<readonly z.ZodObject[]>>(choice: T, shape: z.ZodRawShape) =>
  z.union(choice.options.map((arm) => arm.extend(shape)));

export const NumericCheckSchema = z
  .object({
    value: z.number().int().optional(),
    threshold: z.number().int().optional()
  })
  .superRefine((data, ctx) => {
    if (!(data.value > 0)) {
      ctx.addIssue({
        code: 'custom',
        message: 'ValuePositive: condition failed in NumericCheck',
        path: ['ValuePositive']
      });
    }
    if (!(data.value < data.threshold)) {
      ctx.addIssue({
        code: 'custom',
        message: 'ValueBelowThreshold: condition failed in NumericCheck',
        path: ['ValueBelowThreshold']
      });
    }
    if (!(data.value !== 0)) {
      ctx.addIssue({
        code: 'custom',
        message: 'ValueNotZero: condition failed in NumericCheck',
        path: ['ValueNotZero']
      });
    }
  });
export type NumericCheck = z.infer<typeof NumericCheckSchema>;
