// SPDX-License-Identifier: MIT
// Generated by @rune-langium/codegen — do not edit
// Source namespace: test.rules

import { z } from 'zod';

// --- rune-codegen runtime helpers (inlined) ---
const runeCheckOneOf = (values: (unknown | undefined | null)[]): boolean =>
  values.filter((v) => v !== undefined && v !== null).length === 1;

const runeCount = (arr: unknown[] | undefined | null): number => arr?.length ?? 0;

const runeAttrExists = (v: unknown): boolean =>
  v !== undefined && v !== null && !(Array.isArray(v) && v.length === 0);
// --- end runtime helpers ---

export const TradeSchema = z.object({
  notional: z.number(),
  active: z.boolean()
});
export type Trade = z.infer<typeof TradeSchema>;

export const validateIsLargeTrade = TradeSchema.refine(
  (data) => data.Trade?.notional > 1000000,
  'IsLargeTrade'
);

export const runeReportRules = {
  IsLargeTrade: { kind: 'eligibility' as const, inputType: 'Trade' }
} as const;
