// SPDX-License-Identifier: MIT
// Generated by @rune-langium/codegen — do not edit
// Source namespace: test.rules

// --- rune-codegen runtime helpers (inlined) ---
const runeCheckOneOf = (values: (unknown | undefined | null)[]): boolean =>
  values.filter((v) => v !== undefined && v !== null).length === 1;

const runeCount = (arr: unknown[] | undefined | null): number => arr?.length ?? 0;

const runeAttrExists = (v: unknown): boolean =>
  v !== undefined && v !== null && !(Array.isArray(v) && v.length === 0);
// --- end runtime helpers ---

export interface TradeShape {
  notional: number;
  active: boolean;
}

export class Trade implements TradeShape {
  notional: number;
  active: boolean;

  constructor(data: TradeShape) {
    this.notional = data.notional as typeof this.notional;
    this.active = data.active as typeof this.active;
  }

  static from(json: unknown): Trade {
    if (!isTrade(json)) {
      throw new TypeError('not a Trade: ' + JSON.stringify(json).slice(0, 100));
    }
    return new Trade(json as TradeShape);
  }
}

export function isTrade(x: unknown): x is Trade {
  if (typeof x !== 'object' || x === null) return false;
  if (typeof (x as Record<string, unknown>).notional !== 'number') return false;
  if (typeof (x as Record<string, unknown>).active !== 'boolean') return false;
  return true;
}

export function validateIsLargeTrade(trade: TradeShape): boolean {
  return trade.Trade?.notional > 1000000;
}

export const runeReportRules = {
  IsLargeTrade: { kind: 'eligibility' as const, inputType: 'Trade' }
} as const;
// (functions emitted by Phase 8b appear below this line)
