// SPDX-License-Identifier: MIT
// Generated by @rune-langium/codegen — do not edit
// Source namespace: test.funcs.preconditionAlias

// --- rune-codegen runtime helpers (inlined) ---
const runeValueKey = (value: unknown): string => {
  if (value == null) return 'null';
  if (typeof value !== 'object') return typeof value + ':' + String(value);
  if (Array.isArray(value)) return 'array:' + JSON.stringify(value.map(runeValueKey));
  const tag = Object.prototype.toString.call(value);
  if (/^\[object Temporal\.(PlainDate|PlainTime|PlainDateTime|ZonedDateTime|Instant|PlainYearMonth|PlainMonthDay|Duration)\]$/.test(tag)) return tag + ':' + String(value);
  const fields = value as Record<string, unknown>;
  return 'object:' + JSON.stringify(Object.keys(fields).sort().filter((key) => fields[key] != null).map((key) => [key, runeValueKey(fields[key])]));
};
const runeValueEquals = (left: unknown, right: unknown): boolean => runeValueKey(left) === runeValueKey(right);

const runeCheckOneOf = (values: unknown[]): boolean =>
  values.filter((v) => v !== undefined && v !== null && !(Array.isArray(v) && v.length === 0)).length === 1;

const runeCount = (value: unknown): number => Array.isArray(value) ? value.length : value == null ? 0 : 1;

const runeAttrExists = (v: unknown): boolean =>
  v !== undefined && v !== null && !(Array.isArray(v) && v.length === 0);

const runeToDate = (v: unknown): string | undefined =>
  typeof v === 'string' && /^\d{4}-\d{2}-\d{2}$/.test(v) ? v : undefined;

const runeToTime = (v: unknown): string | undefined =>
  typeof v === 'string' && /^\d{2}:\d{2}:\d{2}(\.\d+)?$/.test(v) ? v : undefined;

const runeToDateTime = (v: unknown): string | undefined =>
  typeof v === 'string' && /^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(\.\d+)?$/.test(v) ? v : undefined;

const runeToZonedDateTime = (v: unknown): string | undefined =>
  typeof v === 'string' && /^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(\.\d+)?(Z|[+-]\d{2}:\d{2})(\[[^\]]+\])?$/.test(v)
    ? v
    : undefined;
// --- end runtime helpers ---

export interface WrapperShape {
  payload?: string;
}

export class Wrapper implements WrapperShape {
  payload?: string;

  constructor(data: WrapperShape) {
    this.payload = data.payload;
  }

  static from(json: unknown): Wrapper {
    if (!isWrapper(json)) {
      throw new TypeError('not a Wrapper: ' + JSON.stringify(json).slice(0, 100));
    }
    return new Wrapper(json as WrapperShape);
  }
}

export function isWrapper(x: unknown): x is Wrapper {
  if (typeof x !== 'object' || x === null) return false;
  if ((x as Record<string, unknown>).payload !== undefined && typeof (x as Record<string, unknown>).payload !== 'string') return false;
  return true;
}


type RuneFuncData<T> = T extends readonly (infer I)[]
  ? RuneFuncData<I>[]
  : T extends (...args: never[]) => unknown
    ? never
    : T extends object
      ? { [K in keyof T as T[K] extends (...args: never[]) => unknown ? never : K]: RuneFuncData<T[K]> }
      : T;

export function UsePayload(input: { wrapper: RuneFuncData<WrapperShape> }): string {
  let result: string | undefined;
  const payload = input.wrapper?.payload;
  if (!runeAttrExists(payload)) {
    throw new Error('Diagnostic: PayloadExists: payload must be present in UsePayload');
  }
  result = payload;
  if (result == null) throw new Error("Function 'UsePayload' produced no result");
  return result;
}
