// SPDX-License-Identifier: MIT
// Generated by @rune-langium/codegen — do not edit
// Source namespace: test.funcs.preconditionAlias

// --- rune-codegen runtime helpers (inlined) ---
const runeCheckOneOf = (values: (unknown | undefined | null)[]): boolean =>
  values.filter((v) => v !== undefined && v !== null).length === 1;

const runeCount = (arr: unknown[] | undefined | null): number => arr?.length ?? 0;

const runeAttrExists = (v: unknown): boolean =>
  v !== undefined && v !== null && !(Array.isArray(v) && v.length === 0);

const runeToDate = (v: unknown): string | undefined =>
  typeof v === 'string' && /^\d{4}-\d{2}-\d{2}$/.test(v) ? v : undefined;

const runeToTime = (v: unknown): string | undefined =>
  typeof v === 'string' && /^\d{2}:\d{2}:\d{2}(\.\d+)?$/.test(v) ? v : undefined;

const runeToDateTime = (v: unknown): string | undefined =>
  typeof v === 'string' && /^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(\.\d+)?$/.test(v) ? v : undefined;

const runeToZonedDateTime = (v: unknown): string | undefined =>
  typeof v === 'string' && /^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(\.\d+)?(Z|[+-]\d{2}:\d{2})(\[[^\]]+\])?$/.test(v)
    ? v
    : undefined;
// --- end runtime helpers ---

export interface WrapperShape {
  payload?: string;
}

export class Wrapper implements WrapperShape {
  payload?: string;

  constructor(data: WrapperShape) {
    this.payload = data.payload as typeof this.payload;
  }

  static from(json: unknown): Wrapper {
    if (!isWrapper(json)) {
      throw new TypeError('not a Wrapper: ' + JSON.stringify(json).slice(0, 100));
    }
    return new Wrapper(json as WrapperShape);
  }
}

export function isWrapper(x: unknown): x is Wrapper {
  if (typeof x !== 'object' || x === null) return false;
  if ((x as Record<string, unknown>).payload !== undefined && typeof (x as Record<string, unknown>).payload !== 'string') return false;
  return true;
}

// (functions emitted by Phase 8b appear below this line)

export function UsePayload(input: { wrapper: Wrapper }): string {
  let result: string;
  const payload = input.wrapper?.payload;
  if (!runeAttrExists(payload)) {
    throw new Error('Diagnostic: PayloadExists: payload must be present in UsePayload');
  }
  result = payload;
  return result;
}
