// SPDX-License-Identifier: MIT
// Generated by @rune-langium/codegen — do not edit
// Source namespace: test.funcs.constructor

// --- rune-codegen runtime helpers (inlined) ---
const runeCheckOneOf = (values: (unknown | undefined | null)[]): boolean =>
  values.filter((v) => v !== undefined && v !== null).length === 1;

const runeCount = (arr: unknown[] | undefined | null): number => arr?.length ?? 0;

const runeAttrExists = (v: unknown): boolean =>
  v !== undefined && v !== null && !(Array.isArray(v) && v.length === 0);
// --- end runtime helpers ---

export interface PointShape {
  x: number;
  y: number;
}

export class Point implements PointShape {
  x: number;
  y: number;

  constructor(data: PointShape) {
    this.x = data.x as typeof this.x;
    this.y = data.y as typeof this.y;
  }

  static from(json: unknown): Point {
    if (!isPoint(json)) {
      throw new TypeError('not a Point: ' + JSON.stringify(json).slice(0, 100));
    }
    return new Point(json as PointShape);
  }
}

export function isPoint(x: unknown): x is Point {
  if (typeof x !== 'object' || x === null) return false;
  if (typeof (x as Record<string, unknown>).x !== 'number') return false;
  if (typeof (x as Record<string, unknown>).y !== 'number') return false;
  return true;
}

export interface BoxShape {
  origin: Point;
  width: number;
}

export class Box implements BoxShape {
  origin: Point;
  width: number;

  constructor(data: BoxShape) {
    this.origin = data.origin as typeof this.origin;
    this.width = data.width as typeof this.width;
  }

  static from(json: unknown): Box {
    if (!isBox(json)) {
      throw new TypeError('not a Box: ' + JSON.stringify(json).slice(0, 100));
    }
    return new Box(json as BoxShape);
  }
}

export function isBox(x: unknown): x is Box {
  if (typeof x !== 'object' || x === null) return false;
  if ((x as Record<string, unknown>).origin === undefined) return false;
  if (typeof (x as Record<string, unknown>).width !== 'number') return false;
  return true;
}

// (functions emitted by Phase 8b appear below this line)

export function MakePoint(input: { x: number; y: number }): Point {
  let result: Point;
  result = { x: input.x, y: input.y };
  return result;
}

export function MakeEmptyBox(input: { w: number }): Box {
  let result: Box;
  result = { origin: {}, width: input.w };
  return result;
}
