// SPDX-License-Identifier: MIT
// Generated by @rune-langium/codegen — do not edit
// Source namespace: test.funcs.constructor

// --- rune-codegen runtime helpers (inlined) ---
const runeValueKey = (value: unknown): string => {
  if (value == null) return 'null';
  if (typeof value !== 'object') return typeof value + ':' + String(value);
  if (Array.isArray(value)) return 'array:' + JSON.stringify(value.map(runeValueKey));
  const fields = value as Record<string, unknown>;
  return 'object:' + JSON.stringify(Object.keys(fields).sort().filter((key) => fields[key] != null).map((key) => [key, runeValueKey(fields[key])]));
};
const runeValueEquals = (left: unknown, right: unknown): boolean => runeValueKey(left) === runeValueKey(right);

const runeCheckOneOf = (values: unknown[]): boolean =>
  values.filter((v) => v !== undefined && v !== null && !(Array.isArray(v) && v.length === 0)).length === 1;

const runeCount = (value: unknown): number => Array.isArray(value) ? value.length : value == null ? 0 : 1;

const runeAttrExists = (v: unknown): boolean =>
  v !== undefined && v !== null && !(Array.isArray(v) && v.length === 0);

const runeToDate = (v: unknown): string | undefined =>
  typeof v === 'string' && /^\d{4}-\d{2}-\d{2}$/.test(v) ? v : undefined;

const runeToTime = (v: unknown): string | undefined =>
  typeof v === 'string' && /^\d{2}:\d{2}:\d{2}(\.\d+)?$/.test(v) ? v : undefined;

const runeToDateTime = (v: unknown): string | undefined =>
  typeof v === 'string' && /^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(\.\d+)?$/.test(v) ? v : undefined;

const runeToZonedDateTime = (v: unknown): string | undefined =>
  typeof v === 'string' && /^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(\.\d+)?(Z|[+-]\d{2}:\d{2})(\[[^\]]+\])?$/.test(v)
    ? v
    : undefined;
// --- end runtime helpers ---

export interface PointShape {
  x: number;
  y: number;
}

export class Point implements PointShape {
  x: number;
  y: number;

  constructor(data: PointShape) {
    this.x = data.x;
    this.y = data.y;
  }

  static from(json: unknown): Point {
    if (!isPoint(json)) {
      throw new TypeError('not a Point: ' + JSON.stringify(json).slice(0, 100));
    }
    return new Point(json as PointShape);
  }
}

export function isPoint(x: unknown): x is Point {
  if (typeof x !== 'object' || x === null) return false;
  if (typeof (x as Record<string, unknown>).x !== 'number') return false;
  if (typeof (x as Record<string, unknown>).y !== 'number') return false;
  return true;
}

export interface BoxShape {
  origin: Point;
  width: number;
}

export class Box implements BoxShape {
  origin: Point;
  width: number;

  constructor(data: BoxShape) {
    this.origin = data.origin;
    this.width = data.width;
  }

  static from(json: unknown): Box {
    if (!isBox(json)) {
      throw new TypeError('not a Box: ' + JSON.stringify(json).slice(0, 100));
    }
    return new Box(json as BoxShape);
  }
}

export function isBox(x: unknown): x is Box {
  if (typeof x !== 'object' || x === null) return false;
  if ((x as Record<string, unknown>).origin === undefined) return false;
  if (typeof (x as Record<string, unknown>).width !== 'number') return false;
  return true;
}


type RuneFuncData<T> = T extends readonly (infer I)[]
  ? RuneFuncData<I>[]
  : T extends (...args: never[]) => unknown
    ? never
    : T extends object
      ? { [K in keyof T as T[K] extends (...args: never[]) => unknown ? never : K]: RuneFuncData<T[K]> }
      : T;

export function MakePoint(input: { x: number; y: number }): RuneFuncData<PointShape> {
  let result: RuneFuncData<PointShape> | undefined;
  result = { x: input.x, y: input.y };
  if (result == null) throw new Error("Function 'MakePoint' produced no result");
  return result;
}

export function MakeEmptyBox(input: { w: number }): RuneFuncData<BoxShape> {
  let result: RuneFuncData<BoxShape> | undefined;
  result = { origin: {}, width: input.w };
  if (result == null) throw new Error("Function 'MakeEmptyBox' produced no result");
  return result;
}
