// SPDX-License-Identifier: MIT
// Generated by @rune-langium/codegen — do not edit
// Source namespace: test.cond.literals

import { z } from 'zod';

// --- rune-codegen runtime helpers (inlined) ---
const runeCheckOneOf = (values: (unknown | undefined | null)[]): boolean =>
  values.filter((v) => v !== undefined && v !== null).length === 1;

const runeCount = (arr: unknown[] | undefined | null): number => arr?.length ?? 0;

const runeAttrExists = (v: unknown): boolean =>
  v !== undefined && v !== null && !(Array.isArray(v) && v.length === 0);

const runeToDate = (v: unknown): string | undefined =>
  typeof v === 'string' && /^\d{4}-\d{2}-\d{2}$/.test(v) ? v : undefined;

const runeToTime = (v: unknown): string | undefined =>
  typeof v === 'string' && /^\d{2}:\d{2}:\d{2}(\.\d+)?$/.test(v) ? v : undefined;

const runeToDateTime = (v: unknown): string | undefined =>
  typeof v === 'string' && /^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(\.\d+)?$/.test(v) ? v : undefined;

const runeToZonedDateTime = (v: unknown): string | undefined =>
  typeof v === 'string' && /^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(\.\d+)?(Z|[+-]\d{2}:\d{2})(\[[^\]]+\])?$/.test(v)
    ? v
    : undefined;
// --- end runtime helpers ---

const runeExtendChoice = <T extends z.ZodUnion<readonly z.ZodObject[]>>(choice: T, shape: z.ZodRawShape) =>
  z.union(choice.options.map((arm) => arm.extend(shape)));

export const WithLiteralsSchema = z
  .object({
    score: z.number().int().optional(),
    name: z.string().optional(),
    active: z.boolean().optional()
  })
  .superRefine((data, ctx) => {
    if (!(data.score === 42)) {
      ctx.addIssue({
        code: 'custom',
        message: 'ScoreCheck: condition failed in WithLiterals',
        path: ['ScoreCheck']
      });
    }
    if (!(data.name === 'hello')) {
      ctx.addIssue({
        code: 'custom',
        message: 'NameCheck: condition failed in WithLiterals',
        path: ['NameCheck']
      });
    }
    if (!(data.active === true)) {
      ctx.addIssue({
        code: 'custom',
        message: 'ActiveCheck: condition failed in WithLiterals',
        path: ['ActiveCheck']
      });
    }
  });
export type WithLiterals = z.infer<typeof WithLiteralsSchema>;
