// SPDX-License-Identifier: FSL-1.1-ALv2
// Copyright (c) 2026 Pradeep Mouli

/**
 * Server-side curated bundle fetcher for the /api/parse Pages Function.
 *
 * Fetches the **pre-parsed** serialized workspace artifact published at
 * `${MIRROR}/{id}/latest.serialized.json.gz` and maps each entry to the
 * CuratedDocument shape consumed by /api/parse's response builder.
 *
 * History: the original implementation (PR #159) fetched the source
 * `archives/{version}.tar.gz` and re-parsed every file through Langium
 * services here in the Pages Function. That works for small bundles but
 * blows the 128 MiB per-invocation memory ceiling for CDM (53 MB
 * compressed → 500 MB+ uncompressed source → langium AST retention →
 * giant JSON.stringify of the response). The function would silently
 * return 502 with `Ok` in wrangler tail — the OOM happens after our
 * handler returns, during CF-side response serialization.
 *
 * The curated-mirror already produces a pre-parsed JSON artifact via the
 * `curated-artifacts.yml` CI workflow (the cron Worker can't build it
 * because IT also OOMs on CDM; CI runs with --max-old-space-size=4096).
 * The artifact is 4 MB compressed / 50 MB decompressed for CDM — well
 * inside the function memory budget — and contains per-document
 * `modelJson` strings + `exports` arrays. We just pass them through.
 *
 * apps/studio/src/services/curated-loader.ts already fetches the same
 * artifact for the in-browser path; this file is the server-side mirror
 * of that logic.
 */

import { inflate } from 'pako';
import {
  CuratedSerializedWorkspaceArtifactSchema,
  type CuratedSerializedWorkspaceArtifact
} from '@rune-langium/curated-schema';

const CURATED_MIRROR_BASE = 'https://www.daikonic.dev/curated';

export interface CuratedDocument {
  uri: string;
  content: string;
  serializedModel: string;
  exports: Array<{ type: string; name: string; path: string }>;
}

export class CuratedBundleUnavailableError extends Error {
  constructor(
    public readonly bundleId: string,
    public readonly version: string,
    public readonly status?: number,
    public readonly cause?: unknown
  ) {
    super(`curated_bundle_unavailable: ${bundleId}@${version}${status ? ` (HTTP ${status})` : ''}`);
    this.name = 'CuratedBundleUnavailableError';
  }
}

/**
 * Per-isolate cache keyed by `${id}@${version}`. Cloudflare Pages Functions
 * reuse the same isolate across many requests; without a cache the
 * debounced editor reparse (every keystroke) would refetch + reinflate +
 * reparse the artifact, wasting CPU + bandwidth.
 *
 * We cache the Promise (not the resolved value) so concurrent requests
 * for the same bundle dedupe to a single fetch. On failure we evict the
 * entry so the next request retries.
 */
const bundleCache = new Map<string, Promise<CuratedDocument[]>>();

export async function fetchCuratedBundle(id: string, version: string): Promise<CuratedDocument[]> {
  const cacheable = version !== 'latest';
  const cacheKey = `${id}@${version}`;
  if (cacheable) {
    const hit = bundleCache.get(cacheKey);
    if (hit) return hit;
  }

  const work = fetchSerializedArtifact(id, version);
  if (cacheable) {
    bundleCache.set(cacheKey, work);
    work.catch(() => {
      if (bundleCache.get(cacheKey) === work) bundleCache.delete(cacheKey);
    });
  }
  return work;
}

async function fetchSerializedArtifact(id: string, version: string): Promise<CuratedDocument[]> {
  // Only `latest.serialized.json.gz` is published; per-version artifacts
  // aren't generated by the CI workflow today. Versioned cache hits use
  // the same artifact (curated bundles are point-in-time-ish — the
  // version field on the request is informational, not authoritative).
  const url = `${CURATED_MIRROR_BASE}/${id}/latest.serialized.json.gz`;

  let res: Response;
  try {
    // Accept-Encoding: identity disables HTTP-level transport compression on
    // the subrequest. The artifact body is a gzip FILE (Content-Type:
    // application/gzip) that we inflate ourselves; if CF / the upstream
    // applied Content-Encoding: gzip on top of it, fetch() would
    // auto-decompress and our subsequent inflate() would fail on what
    // looks like JSON bytes. Pinning identity keeps the wire bytes raw.
    res = await fetch(url, { headers: { 'Accept-Encoding': 'identity' } });
  } catch (err) {
    throw new CuratedBundleUnavailableError(id, version, undefined, err);
  }
  if (!res.ok) {
    throw new CuratedBundleUnavailableError(id, version, res.status);
  }

  // Pull the body into a Uint8Array, inflate, decode, JSON.parse. Each
  // step's intermediate is dropped before the next allocation so peak
  // memory stays close to the largest single representation (~150 MB
  // for the parsed object tree on CDM — fits in the 128 MiB ceiling
  // because V8 doesn't reserve the entire heap upfront).
  const gzBuffer = new Uint8Array(await res.arrayBuffer());
  let jsonText: string;
  try {
    jsonText = new TextDecoder('utf-8').decode(inflate(gzBuffer));
  } catch (err) {
    throw new CuratedBundleUnavailableError(id, version, undefined, err);
  }

  let rawJson: unknown;
  try {
    rawJson = JSON.parse(jsonText);
  } catch (err) {
    throw new CuratedBundleUnavailableError(id, version, undefined, err);
  }

  const parsed = CuratedSerializedWorkspaceArtifactSchema.safeParse(rawJson);
  if (!parsed.success) {
    throw new CuratedBundleUnavailableError(
      id,
      version,
      undefined,
      new Error(`artifact schema mismatch: ${parsed.error.message}`)
    );
  }

  return toDocuments(id, parsed.data);
}

function toDocuments(bundleId: string, artifact: CuratedSerializedWorkspaceArtifact): CuratedDocument[] {
  // The /api/parse response shape uses { uri, content, serializedModel,
  // exports } per document. The artifact carries `path`, `modelJson`,
  // and `exports?`. `content` (raw source text) is not part of the
  // serialized artifact — the browser worker's hydrate handler doesn't
  // need it (it deserializes from modelJson). Emit empty content to
  // keep the shape consistent without inventing data we don't have.
  return artifact.documents.map((doc) => ({
    uri: `${bundleId}/${doc.path}`,
    content: '',
    serializedModel: doc.modelJson,
    exports: doc.exports ?? []
  }));
}
