// SPDX-License-Identifier: MIT
// Generated by @rune-langium/codegen — do not edit
// Source namespace: test.cardinality

import { z } from 'zod';

// --- rune-codegen runtime helpers (inlined) ---
const runeCheckOneOf = (values: (unknown | undefined | null)[]): boolean =>
  values.filter((v) => v !== undefined && v !== null).length === 1;

const runeCount = (arr: unknown[] | undefined | null): number => arr?.length ?? 0;

const runeAttrExists = (v: unknown): boolean =>
  v !== undefined && v !== null && !(Array.isArray(v) && v.length === 0);
// --- end runtime helpers ---

export const CardTestSchema = z.object({
  scalarAttr: z.string(),
  optionalAttr: z.string().optional(),
  zeroOrMore: z.array(z.string()),
  oneOrMore: z.array(z.string()).min(1),
  bounded: z.array(z.string()).min(2).max(5),
  exact: z.array(z.string()).length(3)
});
export type CardTest = z.infer<typeof CardTestSchema>;
