// SPDX-License-Identifier: MIT
// Generated by @rune-langium/codegen — do not edit
// Source namespace: test.cond.existsabsent

import { z } from 'zod';

// --- rune-codegen runtime helpers (inlined) ---
const runeCheckOneOf = (values: (unknown | undefined | null)[]): boolean =>
  values.filter((v) => v !== undefined && v !== null).length === 1;

const runeCount = (arr: unknown[] | undefined | null): number => arr?.length ?? 0;

const runeAttrExists = (v: unknown): boolean =>
  v !== undefined && v !== null && !(Array.isArray(v) && v.length === 0);
// --- end runtime helpers ---

export const HasASchema = z
  .object({
    a: z.string().optional()
  })
  .refine((data) => runeAttrExists(data.a), 'AExists: a must be present in HasA');
export type HasA = z.infer<typeof HasASchema>;

export const HasNoBSchema = z
  .object({
    b: z.string().optional()
  })
  .refine((data) => !runeAttrExists(data.b), 'BAbsent: b must be absent in HasNoB');
export type HasNoB = z.infer<typeof HasNoBSchema>;
