// SPDX-License-Identifier: MIT
// Generated by @rune-langium/codegen — do not edit
// Source namespace: test.cond.setops

import { z } from 'zod';

// --- rune-codegen runtime helpers (inlined) ---
const runeCheckOneOf = (values: (unknown | undefined | null)[]): boolean =>
  values.filter((v) => v !== undefined && v !== null).length === 1;

const runeCount = (arr: unknown[] | undefined | null): number => arr?.length ?? 0;

const runeAttrExists = (v: unknown): boolean =>
  v !== undefined && v !== null && !(Array.isArray(v) && v.length === 0);
// --- end runtime helpers ---

export const SetOpsCheckSchema = z
  .object({
    items: z.array(z.string()),
    allowed: z.array(z.string())
  })
  .refine(
    (data) => !(data.items ?? []).some((v) => (data.allowed ?? []).includes(v)),
    'ItemsDisjoint: condition failed in SetOpsCheck'
  );
export type SetOpsCheck = z.infer<typeof SetOpsCheckSchema>;
