// SPDX-License-Identifier: MIT
// Generated by @rune-langium/codegen — do not edit
// Source namespace: test.enums

import { z } from 'zod';

// --- rune-codegen runtime helpers (inlined) ---
const runeCheckOneOf = (values: (unknown | undefined | null)[]): boolean =>
  values.filter((v) => v !== undefined && v !== null).length === 1;

const runeCount = (arr: unknown[] | undefined | null): number => arr?.length ?? 0;

const runeAttrExists = (v: unknown): boolean =>
  v !== undefined && v !== null && !(Array.isArray(v) && v.length === 0);
// --- end runtime helpers ---

export const ColorEnumSchema = z.enum(['Red', 'Green', 'Blue']);
export type ColorEnum = z.infer<typeof ColorEnumSchema>;

export const StatusEnumSchema = z.enum(['Active', 'Inactive', 'Pending']);
export type StatusEnum = z.infer<typeof StatusEnumSchema>;

export const StatusEnumDisplayNames: Record<StatusEnum, string> = {
  'Active': "Active Status",
  'Inactive': "Inactive Status",
  'Pending': "Pending \"Review\""
};
