// SPDX-License-Identifier: MIT
// Generated by @rune-langium/codegen — do not edit
// Source namespace: test.cond.then

import { z } from 'zod';

// --- rune-codegen runtime helpers (inlined) ---
const runeCheckOneOf = (values: (unknown | undefined | null)[]): boolean =>
  values.filter((v) => v !== undefined && v !== null).length === 1;

const runeCount = (arr: unknown[] | undefined | null): number => arr?.length ?? 0;

const runeAttrExists = (v: unknown): boolean =>
  v !== undefined && v !== null && !(Array.isArray(v) && v.length === 0);
// --- end runtime helpers ---

export const ThenCheckSchema = z
  .object({
    items: z.array(z.number().int())
  })
  .refine(
    (data) => runeCount([...new Set(data.items ?? [])]) > 0,
    'HasDistinct: condition failed in ThenCheck'
  );
export type ThenCheck = z.infer<typeof ThenCheckSchema>;
