// SPDX-License-Identifier: MIT
// Copyright (c) 2026 Pradeep Mouli
import { describe, it, expect } from 'vitest';
import { dialectFor } from '../src/emit/sql-dialect.js';

describe('sql-dialect', () => {
  it('quotes identifiers per dialect', () => {
    expect(dialectFor('postgres').quote('Trade')).toBe('"Trade"');
    expect(dialectFor('sqlserver').quote('Trade')).toBe('[Trade]');
  });
  it('maps builtins to dialect column types', () => {
    const pg = dialectFor('postgres');
    expect(pg.columnType('string')).toBe('TEXT');
    expect(pg.columnType('boolean')).toBe('BOOLEAN');
    expect(pg.columnType('int')).toBe('INTEGER');
    expect(pg.columnType('number')).toBe('NUMERIC');
    expect(pg.columnType('date')).toBe('DATE');
    expect(pg.columnType('dateTime')).toBe('TIMESTAMP');
    const ss = dialectFor('sqlserver');
    expect(ss.columnType('string')).toBe('NVARCHAR(MAX)');
    expect(ss.columnType('boolean')).toBe('BIT');
    expect(ss.columnType('dateTime')).toBe('DATETIME2');
  });
  it('falls back to TEXT/NVARCHAR for unknown builtins', () => {
    expect(dialectFor('postgres').columnType('mysteryType')).toBe('TEXT');
    expect(dialectFor('sqlserver').columnType('mysteryType')).toBe('NVARCHAR(MAX)');
  });
  it('renders a surrogate primary-key column', () => {
    expect(dialectFor('postgres').pkColumn('id')).toBe('"id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY');
    expect(dialectFor('sqlserver').pkColumn('id')).toBe('[id] BIGINT IDENTITY(1,1) PRIMARY KEY');
  });
});
