// SPDX-License-Identifier: MIT
// Copyright (c) 2026 Pradeep Mouli
import { describe, it, expect } from 'vitest';
import { createRuneDslServices } from '@rune-langium/core';
import { URI } from 'langium';
import { Parser } from 'node-sql-parser';
import { generate } from '../src/index.js';

async function gen(source: string, sql: Record<string, unknown> = {}) {
  const { RuneDsl } = createRuneDslServices();
  const doc = RuneDsl.shared.workspace.LangiumDocumentFactory.fromString(source, URI.parse('inmemory:///t.rosetta'));
  await RuneDsl.shared.workspace.DocumentBuilder.build([doc], { validation: false });
  return generate(doc, { target: 'sql', sql });
}
/** Parsing throws on invalid DDL — a structural validity assertion with no DB. */
function assertParses(ddl: string, database: 'postgresql' | 'transactsql' = 'postgresql') {
  new Parser().astify(ddl, { database });
}

describe('SqlNamespaceEmitter — scalar columns + enums', () => {
  it('emits a CREATE TABLE with a surrogate PK and typed columns; NOT NULL from cardinality', async () => {
    const out = await gen(`namespace test.basic

type Quantity:
  amount number (1..1)
  currency string (0..1)
`);
    expect(out).toHaveLength(1);
    expect(out[0]!.relativePath).toBe('test/basic.sql');
    const ddl = out[0]!.content;
    assertParses(ddl);
    expect(ddl).toContain('CREATE TABLE "Quantity"');
    expect(ddl).toMatch(/"id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY/);
    expect(ddl).toMatch(/"amount" NUMERIC NOT NULL/);
    expect(ddl).toMatch(/"currency" TEXT(?! NOT NULL)/); // (0..1) → nullable
    expect(out[0]!.diagnostics.filter((d) => d.severity === 'error')).toHaveLength(0);
  });

  it('emits an enum column with a CHECK constraint (enumStrategy default "check")', async () => {
    const out = await gen(`namespace test.enums

enum Color:
  Red
  Green

type Paint:
  color Color (1..1)
`);
    const ddl = out[0]!.content;
    assertParses(ddl);
    expect(ddl).toMatch(/"color" TEXT NOT NULL/);
    expect(ddl).toMatch(/CHECK\s*\(\s*"color" IN \('Red', 'Green'\)\s*\)/);
  });

  it('resolves a user-defined type alias to its underlying SQL column type', async () => {
    const out = await gen(`namespace test.alias

typeAlias Amount: number

type Trade:
  notional Amount (1..1)
`);
    const ddl = out[0]!.content;
    assertParses(ddl);
    expect(ddl).toMatch(/"notional" NUMERIC NOT NULL/); // NOT TEXT
  });

  it('renders SQL Server dialect with [brackets] + BIT/NVARCHAR + IDENTITY', async () => {
    const out = await gen(`namespace test.basic

type Flag:
  on boolean (1..1)
  description string (1..1)
`, { dialect: 'sqlserver' });
    const ddl = out[0]!.content;
    assertParses(ddl, 'transactsql');
    expect(ddl).toContain('CREATE TABLE [Flag]');
    expect(ddl).toMatch(/\[id\] BIGINT IDENTITY\(1,1\) PRIMARY KEY/);
    expect(ddl).toMatch(/\[on\] BIT NOT NULL/);
    expect(ddl).toMatch(/\[description\] NVARCHAR\(MAX\) NOT NULL/);
  });
});

describe('SqlNamespaceEmitter — references + cardinality', () => {
  it('scalar reference to another type emits an FK column + REFERENCES', async () => {
    const out = await gen(`namespace test.ref

type Party:
  name string (1..1)

type Trade:
  buyer Party (1..1)
`);
    const ddl = out[0]!.content;
    assertParses(ddl);
    expect(ddl).toMatch(/"buyer_id" BIGINT NOT NULL/);
    expect(ddl).toMatch(/FOREIGN KEY \("buyer_id"\) REFERENCES "Party" ?\("id"\)/);
  });

  it('multi-valued attribute of a type emits a join table with two FKs', async () => {
    const out = await gen(`namespace test.multi

type Leg:
  rate number (1..1)

type Swap:
  legs Leg (1..*)
`);
    const ddl = out[0]!.content;
    assertParses(ddl);
    expect(ddl).toContain('CREATE TABLE "Swap_legs"');
    expect(ddl).toMatch(/"swap_id" BIGINT NOT NULL/);
    expect(ddl).toMatch(/"leg_id" BIGINT NOT NULL/);
    expect(ddl).toMatch(/REFERENCES "Swap" ?\("id"\)/);
    expect(ddl).toMatch(/REFERENCES "Leg" ?\("id"\)/);
  });

  it('multi-valued scalar emits a child value table', async () => {
    const out = await gen(`namespace test.multiscalar

type Basket:
  tags string (0..*)
`);
    const ddl = out[0]!.content;
    assertParses(ddl);
    expect(ddl).toContain('CREATE TABLE "Basket_tags"');
    expect(ddl).toMatch(/"basket_id" BIGINT NOT NULL/);
    expect(ddl).toMatch(/"value" TEXT NOT NULL/);
  });

  it('self-referential multi-valued attribute emits distinct FK columns', async () => {
    const out = await gen(`namespace test.selfref

type Node:
  children Node (0..*)
`);
    const ddl = out[0]!.content;
    assertParses(ddl);
    expect(ddl).toContain('CREATE TABLE "Node_children"');
    // two DISTINCT fk columns, both BIGINT NOT NULL, both REFERENCES "Node"
    expect(ddl).toMatch(/"node_id" BIGINT NOT NULL/);
    expect(ddl).toMatch(/"children_id" BIGINT NOT NULL/);
    expect((ddl.match(/REFERENCES "Node" ?\("id"\)/g) || []).length).toBe(2);
  });
});

describe('SqlNamespaceEmitter — inheritance', () => {
  it('table-per-type: child table shares the PK and FKs to the parent', async () => {
    const out = await gen(`namespace test.inh

type Animal:
  name string (1..1)

type Dog extends Animal:
  breed string (1..1)
`);
    const ddl = out[0]!.content;
    assertParses(ddl);
    expect(ddl).toContain('CREATE TABLE "Animal"');
    expect(ddl).toContain('CREATE TABLE "Dog"');
    // Child PK is also an FK to the parent (shared identity).
    expect(ddl).toMatch(/CREATE TABLE "Dog"[\s\S]*"id" BIGINT PRIMARY KEY/);
    expect(ddl).toMatch(/CREATE TABLE "Dog"[\s\S]*REFERENCES "Animal" ?\("id"\)/);
    expect(ddl).toMatch(/CREATE TABLE "Dog"[\s\S]*"breed" TEXT NOT NULL/);
    // Parent keeps the surrogate identity PK.
    expect(ddl).toMatch(/CREATE TABLE "Animal"[\s\S]*"id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY/);
  });

  it("single-table falls back to table-per-type with an info diagnostic", async () => {
    const out = await gen(`namespace test.inh2

type Base:
  x string (1..1)

type Sub extends Base:
  y string (1..1)
`, { inheritance: 'single-table' });
    const ddl = out[0]!.content;
    assertParses(ddl);
    expect(ddl).toMatch(/CREATE TABLE "Sub"[\s\S]*REFERENCES "Base" ?\("id"\)/);
    expect(out[0]!.diagnostics.some((d) => d.code === 'sql-single-table-unsupported')).toBe(true);
  });
});

describe('SQL single-file layout', () => {
  it("layout 'single-file' concatenates all namespaces into one model.sql", async () => {
    const { RuneDsl } = createRuneDslServices();
    const f = RuneDsl.shared.workspace.LangiumDocumentFactory;
    const a = f.fromString('namespace a\n\ntype X:\n  v string (1..1)\n', URI.parse('inmemory:///a.rosetta'));
    const b = f.fromString('namespace b\n\ntype Y:\n  v string (1..1)\n', URI.parse('inmemory:///b.rosetta'));
    await RuneDsl.shared.workspace.DocumentBuilder.build([a, b], { validation: false });
    const out = await generate([a, b], { target: 'sql', sql: { layout: 'single-file' } });
    const paths = out.map((o) => o.relativePath).sort();
    expect(paths).toEqual(['model.sql']);
    const ddl = out[0]!.content;
    assertParses(ddl);
    expect(ddl).toContain('CREATE TABLE "X"');
    expect(ddl).toContain('CREATE TABLE "Y"');
  });

  it('emits a sql-duplicate-table warning diagnostic when two namespaces define a type with the same name', async () => {
    const { RuneDsl } = createRuneDslServices();
    const f = RuneDsl.shared.workspace.LangiumDocumentFactory;
    const a = f.fromString('namespace ns.a\n\ntype X:\n  v string (1..1)\n', URI.parse('inmemory:///nsa.rosetta'));
    const b = f.fromString('namespace ns.b\n\ntype X:\n  v number (1..1)\n', URI.parse('inmemory:///nsb.rosetta'));
    await RuneDsl.shared.workspace.DocumentBuilder.build([a, b], { validation: false });
    const out = await generate([a, b], { target: 'sql', sql: { layout: 'single-file' } });
    expect(out).toHaveLength(1);
    const diag = out[0]!.diagnostics.find((d) => d.code === 'sql-duplicate-table');
    expect(diag).toBeDefined();
    expect(diag!.severity).toBe('warning');
    expect(diag!.message).toMatch(/X/);
  });
});

describe('SqlNamespaceEmitter — enumStrategy', () => {
  it("enumStrategy 'table' falls back to CHECK with an info diagnostic (not silently)", async () => {
    const out = await gen(`namespace test.enumstrat

enum Color:
  Red
  Green

type Paint:
  color Color (1..1)
`, { enumStrategy: 'table' });
    const ddl = out[0]!.content;
    assertParses(ddl);
    expect(ddl).toMatch(/CHECK\s*\(\s*"color" IN \('Red', 'Green'\)\s*\)/);
    expect(out[0]!.diagnostics.some((d) => d.code === 'sql-enum-table-unsupported')).toBe(true);
  });
});

describe('SqlNamespaceEmitter — unresolved types', () => {
  it('warns (does not silently TEXT) when an attribute type does not resolve', async () => {
    const out = await gen(`namespace test.unresolved

type Trade:
  bar MissingType (1..1)
`);
    const ddl = out[0]!.content;
    assertParses(ddl);
    // Still emits a column (graceful TEXT fallback)…
    expect(ddl).toMatch(/"bar" TEXT NOT NULL/);
    // …but surfaces the unresolved type rather than silently mapping to TEXT.
    expect(out[0]!.diagnostics.some((d) => d.code === 'unresolved-ref')).toBe(true);
  });

  it('does NOT warn for a real builtin', async () => {
    const out = await gen(`namespace test.ok

type T:
  s string (1..1)
`);
    expect(out[0]!.diagnostics.some((d) => d.code === 'unresolved-ref')).toBe(false);
  });
});

describe('SqlNamespaceEmitter — enum edge cases + self-ref', () => {
  it('includes inherited enum members in the CHECK constraint', async () => {
    const out = await gen(`namespace test.enuminh

enum Base:
  A
  B

enum Child extends Base:
  C

type T:
  v Child (1..1)
`);
    const ddl = out[0]!.content;
    assertParses(ddl);
    // CHECK must accept inherited A, B AND own C (order-independent).
    const check = ddl.match(/CHECK \("v" IN \(([^)]*)\)\)/)?.[1] ?? '';
    expect(check).toContain("'A'");
    expect(check).toContain("'B'");
    expect(check).toContain("'C'");
  });

  it('emits no CHECK (and warns) for a valueless enum', async () => {
    const out = await gen(`namespace test.emptyenum

enum Empty:

type T:
  v Empty (1..1)
`);
    const ddl = out[0]!.content;
    assertParses(ddl);
    expect(ddl).toMatch(/"v" TEXT NOT NULL/);
    expect(ddl).not.toContain('IN ()');
    expect(out[0]!.diagnostics.some((d) => d.code === 'sql-empty-enum')).toBe(true);
  });

  it('self-ref join FK stays distinct even when attr name equals the owner type name', async () => {
    const out = await gen(`namespace test.selfref2

type Node:
  node Node (0..*)
`);
    const ddl = out[0]!.content;
    assertParses(ddl);
    expect(ddl).toContain('CREATE TABLE "Node_node"');
    // ownerFk node_id + a DISTINCT target fk (node_target_id), not two node_id.
    expect(ddl).toMatch(/"node_id" BIGINT NOT NULL/);
    expect(ddl).toMatch(/"node_target_id" BIGINT NOT NULL/);
  });
});

describe('SqlNamespaceEmitter — identifier + alias collisions', () => {
  it('renames a user attribute that collides with the synthetic id PK (no duplicate column)', async () => {
    const out = await gen(`namespace test.idcol

type Trade:
  id string (1..1)
`);
    const ddl = out[0]!.content;
    assertParses(ddl); // would throw on duplicate "id" columns
    // PK id stays; the user attr is renamed.
    expect(ddl).toMatch(/"id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY/);
    expect(ddl).toMatch(/"id_" TEXT NOT NULL/);
    expect(out[0]!.diagnostics.some((d) => d.code === 'sql-column-collision')).toBe(true);
  });

  it('treats an alias whose target is unresolved as unresolved (warns, not silent TEXT)', async () => {
    const out = await gen(`namespace test.badalias

typeAlias Amount: MissingType

type Trade:
  notional Amount (1..1)
`);
    const ddl = out[0]!.content;
    assertParses(ddl);
    expect(ddl).toMatch(/"notional" TEXT NOT NULL/);
    expect(out[0]!.diagnostics.some((d) => d.code === 'unresolved-ref')).toBe(true);
  });
});
