// SPDX-License-Identifier: MIT
// Copyright (c) 2026 Pradeep Mouli
import { describe, it, expect } from 'vitest';
import { createRuneDslServices } from '@rune-langium/core';
import { URI } from 'langium';
import { Parser } from 'node-sql-parser';
import { generate } from '../src/index.js';

async function gen(source: string, sql: Record<string, unknown> = {}) {
  const { RuneDsl } = createRuneDslServices();
  const doc = RuneDsl.shared.workspace.LangiumDocumentFactory.fromString(source, URI.parse('inmemory:///t.rosetta'));
  await RuneDsl.shared.workspace.DocumentBuilder.build([doc], { validation: false });
  return generate(doc, { target: 'sql', sql });
}
/** Parsing throws on invalid DDL — a structural validity assertion with no DB. */
function assertParses(ddl: string, database: 'postgresql' | 'transactsql' = 'postgresql') {
  new Parser().astify(ddl, { database });
}

describe('SqlNamespaceEmitter — scalar columns + enums', () => {
  it('emits a CREATE TABLE with a surrogate PK and typed columns; NOT NULL from cardinality', async () => {
    const out = await gen(`namespace test.basic

type Quantity:
  amount number (1..1)
  currency string (0..1)
`);
    expect(out).toHaveLength(1);
    expect(out[0]!.relativePath).toBe('test/basic.sql');
    const ddl = out[0]!.content;
    assertParses(ddl);
    expect(ddl).toContain('CREATE TABLE "Quantity"');
    expect(ddl).toMatch(/"id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY/);
    expect(ddl).toMatch(/"amount" NUMERIC NOT NULL/);
    expect(ddl).toMatch(/"currency" TEXT(?! NOT NULL)/); // (0..1) → nullable
    expect(out[0]!.diagnostics.filter((d) => d.severity === 'error')).toHaveLength(0);
  });

  it('emits an enum column with a CHECK constraint (enumStrategy default "check")', async () => {
    const out = await gen(`namespace test.enums

enum Color:
  Red
  Green

type Paint:
  color Color (1..1)
`);
    const ddl = out[0]!.content;
    assertParses(ddl);
    expect(ddl).toMatch(/"color" TEXT NOT NULL/);
    expect(ddl).toMatch(/CHECK\s*\(\s*"color" IN \('Red', 'Green'\)\s*\)/);
  });

  it('renders SQL Server dialect with [brackets] + BIT/NVARCHAR + IDENTITY', async () => {
    const out = await gen(`namespace test.basic

type Flag:
  on boolean (1..1)
  description string (1..1)
`, { dialect: 'sqlserver' });
    const ddl = out[0]!.content;
    assertParses(ddl, 'transactsql');
    expect(ddl).toContain('CREATE TABLE [Flag]');
    expect(ddl).toMatch(/\[id\] BIGINT IDENTITY\(1,1\) PRIMARY KEY/);
    expect(ddl).toMatch(/\[on\] BIT NOT NULL/);
    expect(ddl).toMatch(/\[description\] NVARCHAR\(MAX\) NOT NULL/);
  });
});

describe('SqlNamespaceEmitter — references + cardinality', () => {
  it('scalar reference to another type emits an FK column + REFERENCES', async () => {
    const out = await gen(`namespace test.ref

type Party:
  name string (1..1)

type Trade:
  buyer Party (1..1)
`);
    const ddl = out[0]!.content;
    assertParses(ddl);
    expect(ddl).toMatch(/"buyer_id" BIGINT NOT NULL/);
    expect(ddl).toMatch(/FOREIGN KEY \("buyer_id"\) REFERENCES "Party" ?\("id"\)/);
  });

  it('multi-valued attribute of a type emits a join table with two FKs', async () => {
    const out = await gen(`namespace test.multi

type Leg:
  rate number (1..1)

type Swap:
  legs Leg (1..*)
`);
    const ddl = out[0]!.content;
    assertParses(ddl);
    expect(ddl).toContain('CREATE TABLE "Swap_legs"');
    expect(ddl).toMatch(/"swap_id" BIGINT NOT NULL/);
    expect(ddl).toMatch(/"leg_id" BIGINT NOT NULL/);
    expect(ddl).toMatch(/REFERENCES "Swap" ?\("id"\)/);
    expect(ddl).toMatch(/REFERENCES "Leg" ?\("id"\)/);
  });

  it('multi-valued scalar emits a child value table', async () => {
    const out = await gen(`namespace test.multiscalar

type Basket:
  tags string (0..*)
`);
    const ddl = out[0]!.content;
    assertParses(ddl);
    expect(ddl).toContain('CREATE TABLE "Basket_tags"');
    expect(ddl).toMatch(/"basket_id" BIGINT NOT NULL/);
    expect(ddl).toMatch(/"value" TEXT/);
  });
});

describe('SqlNamespaceEmitter — inheritance', () => {
  it('table-per-type: child table shares the PK and FKs to the parent', async () => {
    const out = await gen(`namespace test.inh

type Animal:
  name string (1..1)

type Dog extends Animal:
  breed string (1..1)
`);
    const ddl = out[0]!.content;
    assertParses(ddl);
    expect(ddl).toContain('CREATE TABLE "Animal"');
    expect(ddl).toContain('CREATE TABLE "Dog"');
    // Child PK is also an FK to the parent (shared identity).
    expect(ddl).toMatch(/CREATE TABLE "Dog"[\s\S]*"id" BIGINT PRIMARY KEY/);
    expect(ddl).toMatch(/CREATE TABLE "Dog"[\s\S]*REFERENCES "Animal" ?\("id"\)/);
    expect(ddl).toMatch(/CREATE TABLE "Dog"[\s\S]*"breed" TEXT NOT NULL/);
    // Parent keeps the surrogate identity PK.
    expect(ddl).toMatch(/CREATE TABLE "Animal"[\s\S]*"id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY/);
  });

  it("single-table falls back to table-per-type with an info diagnostic", async () => {
    const out = await gen(`namespace test.inh2

type Base:
  x string (1..1)

type Sub extends Base:
  y string (1..1)
`, { inheritance: 'single-table' });
    const ddl = out[0]!.content;
    assertParses(ddl);
    expect(ddl).toMatch(/CREATE TABLE "Sub"[\s\S]*REFERENCES "Base" ?\("id"\)/);
    expect(out[0]!.diagnostics.some((d) => d.code === 'sql-single-table-unsupported')).toBe(true);
  });
});
