// SPDX-License-Identifier: MIT
// Generated by @rune-langium/codegen — do not edit
// Source namespace: test.annotations

// --- rune-codegen runtime helpers (inlined) ---
const runeCheckOneOf = (values: (unknown | undefined | null)[]): boolean =>
  values.filter((v) => v !== undefined && v !== null).length === 1;

const runeCount = (arr: unknown[] | undefined | null): number => arr?.length ?? 0;

const runeAttrExists = (v: unknown): boolean =>
  v !== undefined && v !== null && !(Array.isArray(v) && v.length === 0);

const runeToDate = (v: unknown): string | undefined =>
  typeof v === 'string' && /^\d{4}-\d{2}-\d{2}$/.test(v) ? v : undefined;

const runeToTime = (v: unknown): string | undefined =>
  typeof v === 'string' && /^\d{2}:\d{2}:\d{2}(\.\d+)?$/.test(v) ? v : undefined;

const runeToDateTime = (v: unknown): string | undefined =>
  typeof v === 'string' && /^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(\.\d+)?$/.test(v) ? v : undefined;

const runeToZonedDateTime = (v: unknown): string | undefined =>
  typeof v === 'string' && /^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(\.\d+)?(Z|[+-]\d{2}:\d{2})(\[[^\]]+\])?$/.test(v)
    ? v
    : undefined;
// --- end runtime helpers ---


export interface sourceArgs {
  system: string;
}

export function source(args: sourceArgs): ClassDecorator & PropertyDecorator {
  return (target: any, propertyKey?: any) => {};
}

export interface TradeShape {
  tradeDate: Temporal.PlainDate;
  notional: number;
}

export class Trade implements TradeShape {
  tradeDate: Temporal.PlainDate;
  notional: number;

  constructor(data: TradeShape) {
    this.tradeDate = data.tradeDate as typeof this.tradeDate;
    this.notional = data.notional as typeof this.notional;
  }

  static from(json: unknown): Trade {
    if (!isTrade(json)) {
      throw new TypeError('not a Trade: ' + JSON.stringify(json).slice(0, 100));
    }
    return new Trade(json as TradeShape);
  }
}

export function isTrade(x: unknown): x is Trade {
  if (typeof x !== 'object' || x === null) return false;
  if (!((x as Record<string, unknown>).tradeDate instanceof Temporal.PlainDate)) return false;
  if (typeof (x as Record<string, unknown>).notional !== 'number') return false;
  return true;
}

// (functions emitted by Phase 8b appear below this line)
