// SPDX-License-Identifier: MIT
// Generated by @rune-langium/codegen — do not edit
// Source namespace: test.cond.boolean

import { z } from 'zod';

// --- rune-codegen runtime helpers (inlined) ---
const runeCheckOneOf = (values: (unknown | undefined | null)[]): boolean =>
  values.filter((v) => v !== undefined && v !== null).length === 1;

const runeCount = (arr: unknown[] | undefined | null): number => arr?.length ?? 0;

const runeAttrExists = (v: unknown): boolean =>
  v !== undefined && v !== null && !(Array.isArray(v) && v.length === 0);
// --- end runtime helpers ---

export const BoolCheckSchema = z
  .object({
    a: z.string().optional(),
    b: z.string().optional(),
    c: z.string().optional()
  })
  .superRefine((data, ctx) => {
    if (!(runeAttrExists(data.a) || runeAttrExists(data.b))) {
      ctx.addIssue({
        code: 'custom',
        message: 'AOrB: condition failed in BoolCheck',
        path: ['AOrB']
      });
    }
    if (!(runeAttrExists(data.a) && runeAttrExists(data.b))) {
      ctx.addIssue({
        code: 'custom',
        message: 'AAndB: condition failed in BoolCheck',
        path: ['AAndB']
      });
    }
  });
export type BoolCheck = z.infer<typeof BoolCheckSchema>;
