// SPDX-License-Identifier: MIT
// Generated by @rune-langium/codegen — do not edit
// Source namespace: test.cond.boolean

import { z } from 'zod';

// --- rune-codegen runtime helpers (inlined) ---
const runeCheckOneOf = (values: (unknown | undefined | null)[]): boolean =>
  values.filter((v) => v !== undefined && v !== null).length === 1;

const runeCount = (arr: unknown[] | undefined | null): number => arr?.length ?? 0;

const runeAttrExists = (v: unknown): boolean =>
  v !== undefined && v !== null && !(Array.isArray(v) && v.length === 0);

const runeToDate = (v: unknown): string | undefined =>
  typeof v === 'string' && /^\d{4}-\d{2}-\d{2}$/.test(v) ? v : undefined;

const runeToTime = (v: unknown): string | undefined =>
  typeof v === 'string' && /^\d{2}:\d{2}:\d{2}(\.\d+)?$/.test(v) ? v : undefined;

const runeToDateTime = (v: unknown): string | undefined =>
  typeof v === 'string' && /^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(\.\d+)?$/.test(v) ? v : undefined;

const runeToZonedDateTime = (v: unknown): string | undefined =>
  typeof v === 'string' && /^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(\.\d+)?(Z|[+-]\d{2}:\d{2})(\[[^\]]+\])?$/.test(v)
    ? v
    : undefined;
// --- end runtime helpers ---

export const BoolCheckSchema = z
  .object({
    a: z.string().optional(),
    b: z.string().optional(),
    c: z.string().optional()
  })
  .superRefine((data, ctx) => {
    if (!(runeAttrExists(data.a) || runeAttrExists(data.b))) {
      ctx.addIssue({
        code: 'custom',
        message: 'AOrB: condition failed in BoolCheck',
        path: ['AOrB']
      });
    }
    if (!(runeAttrExists(data.a) && runeAttrExists(data.b))) {
      ctx.addIssue({
        code: 'custom',
        message: 'AAndB: condition failed in BoolCheck',
        path: ['AAndB']
      });
    }
  });
export type BoolCheck = z.infer<typeof BoolCheckSchema>;
