// SPDX-License-Identifier: MIT
// Generated by @rune-langium/codegen — do not edit
// Source namespace: test.basic

// --- rune-codegen runtime helpers (inlined) ---
const runeValueKey = (value: unknown): string => {
  if (value == null) return 'null';
  if (typeof value !== 'object') return typeof value + ':' + String(value);
  if (Array.isArray(value)) return 'array:' + JSON.stringify(value.map(runeValueKey));
  const fields = value as Record<string, unknown>;
  return 'object:' + JSON.stringify(Object.keys(fields).sort().filter((key) => fields[key] != null).map((key) => [key, runeValueKey(fields[key])]));
};
const runeValueEquals = (left: unknown, right: unknown): boolean => runeValueKey(left) === runeValueKey(right);

const runeCheckOneOf = (values: unknown[]): boolean =>
  values.filter((v) => v !== undefined && v !== null && !(Array.isArray(v) && v.length === 0)).length === 1;

const runeCount = (value: unknown): number => Array.isArray(value) ? value.length : value == null ? 0 : 1;

const runeAttrExists = (v: unknown): boolean =>
  v !== undefined && v !== null && !(Array.isArray(v) && v.length === 0);

const runeToDate = (v: unknown): string | undefined =>
  typeof v === 'string' && /^\d{4}-\d{2}-\d{2}$/.test(v) ? v : undefined;

const runeToTime = (v: unknown): string | undefined =>
  typeof v === 'string' && /^\d{2}:\d{2}:\d{2}(\.\d+)?$/.test(v) ? v : undefined;

const runeToDateTime = (v: unknown): string | undefined =>
  typeof v === 'string' && /^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(\.\d+)?$/.test(v) ? v : undefined;

const runeToZonedDateTime = (v: unknown): string | undefined =>
  typeof v === 'string' && /^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(\.\d+)?(Z|[+-]\d{2}:\d{2})(\[[^\]]+\])?$/.test(v)
    ? v
    : undefined;
// --- end runtime helpers ---

export interface EmptyShape {}

export class Empty implements EmptyShape {
  constructor(data: EmptyShape) {}

  static from(json: unknown): Empty {
    if (!isEmpty(json)) {
      throw new TypeError('not a Empty: ' + JSON.stringify(json).slice(0, 100));
    }
    return new Empty(json as EmptyShape);
  }
}

export function isEmpty(x: unknown): x is Empty {
  if (typeof x !== 'object' || x === null) return false;
  return true;
}

export interface PersonShape {
  name: string;
  age: number;
  active: boolean;
  birthday: Temporal.PlainDate;
}

export class Person implements PersonShape {
  name: string;
  age: number;
  active: boolean;
  birthday: Temporal.PlainDate;

  constructor(data: PersonShape) {
    this.name = data.name;
    this.age = data.age;
    this.active = data.active;
    this.birthday = data.birthday;
  }

  static from(json: unknown): Person {
    if (!isPerson(json)) {
      throw new TypeError('not a Person: ' + JSON.stringify(json).slice(0, 100));
    }
    return new Person(json as PersonShape);
  }
}

export function isPerson(x: unknown): x is Person {
  if (typeof x !== 'object' || x === null) return false;
  if (typeof (x as Record<string, unknown>).name !== 'string') return false;
  if (typeof (x as Record<string, unknown>).age !== 'number') return false;
  if (typeof (x as Record<string, unknown>).active !== 'boolean') return false;
  if (!((x as Record<string, unknown>).birthday instanceof Temporal.PlainDate)) return false;
  return true;
}
