// SPDX-License-Identifier: MIT
// Generated by @rune-langium/codegen — do not edit
// Source namespace: test.basic

import { z } from 'zod';

// --- rune-codegen runtime helpers (inlined) ---
const runeCheckOneOf = (values: (unknown | undefined | null)[]): boolean =>
  values.filter((v) => v !== undefined && v !== null).length === 1;

const runeCount = (arr: unknown[] | undefined | null): number => arr?.length ?? 0;

const runeAttrExists = (v: unknown): boolean =>
  v !== undefined && v !== null && !(Array.isArray(v) && v.length === 0);
// --- end runtime helpers ---

export const EmptySchema = z.object({});
export type Empty = z.infer<typeof EmptySchema>;

export const PersonSchema = z.object({
  name: z.string(),
  age: z.number().int(),
  active: z.boolean(),
  birthday: z.string()
});
export type Person = z.infer<typeof PersonSchema>;
