// SPDX-License-Identifier: MIT
// Generated by @rune-langium/codegen — do not edit
// Source namespace: test.basic

// --- rune-codegen runtime helpers (inlined) ---
const runeCheckOneOf = (values: (unknown | undefined | null)[]): boolean =>
  values.filter((v) => v !== undefined && v !== null).length === 1;

const runeCount = (arr: unknown[] | undefined | null): number => arr?.length ?? 0;

const runeAttrExists = (v: unknown): boolean =>
  v !== undefined && v !== null && !(Array.isArray(v) && v.length === 0);
// --- end runtime helpers ---

export interface EmptyShape {}

export class Empty implements EmptyShape {
  constructor(data: EmptyShape) {}

  static from(json: unknown): Empty {
    if (!isEmpty(json)) {
      throw new TypeError('not a Empty: ' + JSON.stringify(json).slice(0, 100));
    }
    return new Empty(json as EmptyShape);
  }
}

export function isEmpty(x: unknown): x is Empty {
  if (typeof x !== 'object' || x === null) return false;
  return true;
}

export interface PersonShape {
  name: string;
  age: number;
  active: boolean;
  birthday: string;
}

export class Person implements PersonShape {
  name: string;
  age: number;
  active: boolean;
  birthday: string;

  constructor(data: PersonShape) {
    this.name = data.name as typeof this.name;
    this.age = data.age as typeof this.age;
    this.active = data.active as typeof this.active;
    this.birthday = data.birthday as typeof this.birthday;
  }

  static from(json: unknown): Person {
    if (!isPerson(json)) {
      throw new TypeError('not a Person: ' + JSON.stringify(json).slice(0, 100));
    }
    return new Person(json as PersonShape);
  }
}

export function isPerson(x: unknown): x is Person {
  if (typeof x !== 'object' || x === null) return false;
  if (typeof (x as Record<string, unknown>).name !== 'string') return false;
  if (typeof (x as Record<string, unknown>).age !== 'number') return false;
  if (typeof (x as Record<string, unknown>).active !== 'boolean') return false;
  if (typeof (x as Record<string, unknown>).birthday !== 'string') return false;
  return true;
}

// (functions emitted by Phase 8b appear below this line)
