// SPDX-License-Identifier: MIT
// Generated by @rune-langium/codegen — do not edit
// Source namespace: test.aliases

// --- rune-codegen runtime helpers (inlined) ---
const runeCheckOneOf = (values: (unknown | undefined | null)[]): boolean =>
  values.filter((v) => v !== undefined && v !== null).length === 1;

const runeCount = (arr: unknown[] | undefined | null): number => arr?.length ?? 0;

const runeAttrExists = (v: unknown): boolean =>
  v !== undefined && v !== null && !(Array.isArray(v) && v.length === 0);
// --- end runtime helpers ---

export type Amount = number;

export type Price = Amount;

export type UnitPrice = Price;
// (functions emitted by Phase 8b appear below this line)
