// SPDX-License-Identifier: MIT
// Generated by @rune-langium/codegen — do not edit
// Source namespace: test.circular

import { z } from 'zod';

// --- rune-codegen runtime helpers (inlined) ---
const runeCheckOneOf = (values: (unknown | undefined | null)[]): boolean =>
  values.filter((v) => v !== undefined && v !== null).length === 1;

const runeCount = (arr: unknown[] | undefined | null): number => arr?.length ?? 0;

const runeAttrExists = (v: unknown): boolean =>
  v !== undefined && v !== null && !(Array.isArray(v) && v.length === 0);
// --- end runtime helpers ---

export interface NodeA {
  child?: NodeB;
}
export interface NodeB {
  parent?: NodeA;
}
export interface SelfRef {
  self?: SelfRef;
}

export const NodeASchema: z.ZodType<NodeA> = z.lazy(() =>
  z.object({
    child: NodeBSchema.optional()
  })
);

export const NodeBSchema: z.ZodType<NodeB> = z.lazy(() =>
  z.object({
    parent: NodeASchema.optional()
  })
);

export const SelfRefSchema: z.ZodType<SelfRef> = z.lazy(() =>
  z.object({
    self: SelfRefSchema.optional()
  })
);
