// SPDX-License-Identifier: MIT
// Generated by @rune-langium/codegen — do not edit
// Source namespace: test.inheritance

// --- rune-codegen runtime helpers (inlined) ---
const runeValueKey = (value: unknown): string => {
  if (value == null) return 'null';
  if (typeof value !== 'object') return typeof value + ':' + String(value);
  if (Array.isArray(value)) return 'array:' + JSON.stringify(value.map(runeValueKey));
  const fields = value as Record<string, unknown>;
  return 'object:' + JSON.stringify(Object.keys(fields).sort().filter((key) => fields[key] != null).map((key) => [key, runeValueKey(fields[key])]));
};
const runeValueEquals = (left: unknown, right: unknown): boolean => runeValueKey(left) === runeValueKey(right);

const runeCheckOneOf = (values: unknown[]): boolean =>
  values.filter((v) => v !== undefined && v !== null && !(Array.isArray(v) && v.length === 0)).length === 1;

const runeCount = (value: unknown): number => Array.isArray(value) ? value.length : value == null ? 0 : 1;

const runeAttrExists = (v: unknown): boolean =>
  v !== undefined && v !== null && !(Array.isArray(v) && v.length === 0);

const runeToDate = (v: unknown): string | undefined =>
  typeof v === 'string' && /^\d{4}-\d{2}-\d{2}$/.test(v) ? v : undefined;

const runeToTime = (v: unknown): string | undefined =>
  typeof v === 'string' && /^\d{2}:\d{2}:\d{2}(\.\d+)?$/.test(v) ? v : undefined;

const runeToDateTime = (v: unknown): string | undefined =>
  typeof v === 'string' && /^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(\.\d+)?$/.test(v) ? v : undefined;

const runeToZonedDateTime = (v: unknown): string | undefined =>
  typeof v === 'string' && /^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(\.\d+)?(Z|[+-]\d{2}:\d{2})(\[[^\]]+\])?$/.test(v)
    ? v
    : undefined;
// --- end runtime helpers ---

export interface AnimalShape {
  name: string;
}

export class Animal implements AnimalShape {
  name: string;

  constructor(data: AnimalShape) {
    this.name = data.name;
  }

  static from(json: unknown): Animal {
    if (!isAnimal(json)) {
      throw new TypeError('not a Animal: ' + JSON.stringify(json).slice(0, 100));
    }
    return new Animal(json as AnimalShape);
  }
}

export function isAnimal(x: unknown): x is Animal {
  if (typeof x !== 'object' || x === null) return false;
  if (typeof (x as Record<string, unknown>).name !== 'string') return false;
  return true;
}

export interface DogShape extends AnimalShape {
  breed: string;
}

export class Dog extends Animal implements DogShape {
  breed: string;

  constructor(data: DogShape) {
    super(data);
    this.breed = data.breed;
  }

  static from(json: unknown): Dog {
    if (!isDog(json)) {
      throw new TypeError('not a Dog: ' + JSON.stringify(json).slice(0, 100));
    }
    return new Dog(json as DogShape);
  }
}

export function isDog(x: unknown): x is Dog;
export function isDog(x: Animal): x is Dog;
export function isDog(x: unknown): x is Dog {
  if (typeof x !== 'object' || x === null) return false;
  if (typeof (x as Record<string, unknown>).name !== 'string') return false;
  if (typeof (x as Record<string, unknown>).breed !== 'string') return false;
  return true;
}

export interface SiblingShape extends AnimalShape {
  age: number;
}

export class Sibling extends Animal implements SiblingShape {
  age: number;

  constructor(data: SiblingShape) {
    super(data);
    this.age = data.age;
  }

  static from(json: unknown): Sibling {
    if (!isSibling(json)) {
      throw new TypeError('not a Sibling: ' + JSON.stringify(json).slice(0, 100));
    }
    return new Sibling(json as SiblingShape);
  }
}

export function isSibling(x: unknown): x is Sibling;
export function isSibling(x: Animal): x is Sibling;
export function isSibling(x: unknown): x is Sibling {
  if (typeof x !== 'object' || x === null) return false;
  if (typeof (x as Record<string, unknown>).name !== 'string') return false;
  if (typeof (x as Record<string, unknown>).age !== 'number') return false;
  return true;
}

export interface PoodleShape extends DogShape {
  size: string;
}

export class Poodle extends Dog implements PoodleShape {
  size: string;

  constructor(data: PoodleShape) {
    super(data);
    this.size = data.size;
  }

  static from(json: unknown): Poodle {
    if (!isPoodle(json)) {
      throw new TypeError('not a Poodle: ' + JSON.stringify(json).slice(0, 100));
    }
    return new Poodle(json as PoodleShape);
  }
}

export function isPoodle(x: unknown): x is Poodle;
export function isPoodle(x: Dog): x is Poodle;
export function isPoodle(x: unknown): x is Poodle {
  if (typeof x !== 'object' || x === null) return false;
  if (typeof (x as Record<string, unknown>).breed !== 'string') return false;
  if (typeof (x as Record<string, unknown>).size !== 'string') return false;
  return true;
}
