// SPDX-License-Identifier: MIT
// Generated by @rune-langium/codegen — do not edit
// Source namespace: test.inheritance

import { z } from 'zod';

// --- rune-codegen runtime helpers (inlined) ---
const runeCheckOneOf = (values: (unknown | undefined | null)[]): boolean =>
  values.filter((v) => v !== undefined && v !== null).length === 1;

const runeCount = (arr: unknown[] | undefined | null): number => arr?.length ?? 0;

const runeAttrExists = (v: unknown): boolean =>
  v !== undefined && v !== null && !(Array.isArray(v) && v.length === 0);
// --- end runtime helpers ---

export const AnimalSchema = z.object({
  name: z.string()
});
export type Animal = z.infer<typeof AnimalSchema>;

export const DogSchema = AnimalSchema.extend({
  breed: z.string()
});
export type Dog = z.infer<typeof DogSchema>;

export const SiblingSchema = AnimalSchema.extend({
  age: z.number().int()
});
export type Sibling = z.infer<typeof SiblingSchema>;

export const PoodleSchema = DogSchema.extend({
  size: z.string()
});
export type Poodle = z.infer<typeof PoodleSchema>;
