// SPDX-License-Identifier: MIT
// Generated by @rune-langium/codegen — do not edit
// Source namespace: test.aliases

// --- rune-codegen runtime helpers (inlined) ---
const runeValueKey = (value: unknown): string => {
  if (value == null) return 'null';
  if (typeof value !== 'object') return typeof value + ':' + String(value);
  if (Array.isArray(value)) return 'array:' + JSON.stringify(value.map(runeValueKey));
  const fields = value as Record<string, unknown>;
  return 'object:' + JSON.stringify(Object.keys(fields).sort().filter((key) => fields[key] != null).map((key) => [key, runeValueKey(fields[key])]));
};
const runeValueEquals = (left: unknown, right: unknown): boolean => runeValueKey(left) === runeValueKey(right);

const runeCheckOneOf = (values: unknown[]): boolean =>
  values.filter((v) => v !== undefined && v !== null && !(Array.isArray(v) && v.length === 0)).length === 1;

const runeCount = (value: unknown): number => Array.isArray(value) ? value.length : value == null ? 0 : 1;

const runeAttrExists = (v: unknown): boolean =>
  v !== undefined && v !== null && !(Array.isArray(v) && v.length === 0);

const runeToDate = (v: unknown): string | undefined =>
  typeof v === 'string' && /^\d{4}-\d{2}-\d{2}$/.test(v) ? v : undefined;

const runeToTime = (v: unknown): string | undefined =>
  typeof v === 'string' && /^\d{2}:\d{2}:\d{2}(\.\d+)?$/.test(v) ? v : undefined;

const runeToDateTime = (v: unknown): string | undefined =>
  typeof v === 'string' && /^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(\.\d+)?$/.test(v) ? v : undefined;

const runeToZonedDateTime = (v: unknown): string | undefined =>
  typeof v === 'string' && /^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(\.\d+)?(Z|[+-]\d{2}:\d{2})(\[[^\]]+\])?$/.test(v)
    ? v
    : undefined;
// --- end runtime helpers ---


export type HomeAddress = AddressShape;
export interface AddressShape {
  street: string;
  city: string;
}

export class Address implements AddressShape {
  street: string;
  city: string;

  constructor(data: AddressShape) {
    this.street = data.street;
    this.city = data.city;
  }

  static from(json: unknown): Address {
    if (!isAddress(json)) {
      throw new TypeError('not a Address: ' + JSON.stringify(json).slice(0, 100));
    }
    return new Address(json as AddressShape);
  }
}

export function isAddress(x: unknown): x is Address {
  if (typeof x !== 'object' || x === null) return false;
  if (typeof (x as Record<string, unknown>).street !== 'string') return false;
  if (typeof (x as Record<string, unknown>).city !== 'string') return false;
  return true;
}
