// SPDX-License-Identifier: MIT
// Generated by @rune-langium/codegen — do not edit
// Source namespace: test.aliases

// --- rune-codegen runtime helpers (inlined) ---
const runeCheckOneOf = (values: (unknown | undefined | null)[]): boolean =>
  values.filter((v) => v !== undefined && v !== null).length === 1;

const runeCount = (arr: unknown[] | undefined | null): number => arr?.length ?? 0;

const runeAttrExists = (v: unknown): boolean =>
  v !== undefined && v !== null && !(Array.isArray(v) && v.length === 0);
// --- end runtime helpers ---


export type HomeAddress = AddressShape;
export interface AddressShape {
  street: string;
  city: string;
}

export class Address implements AddressShape {
  street: string;
  city: string;

  constructor(data: AddressShape) {
    this.street = data.street as typeof this.street;
    this.city = data.city as typeof this.city;
  }

  static from(json: unknown): Address {
    if (!isAddress(json)) {
      throw new TypeError('not a Address: ' + JSON.stringify(json).slice(0, 100));
    }
    return new Address(json as AddressShape);
  }
}

export function isAddress(x: unknown): x is Address {
  if (typeof x !== 'object' || x === null) return false;
  if (typeof (x as Record<string, unknown>).street !== 'string') return false;
  if (typeof (x as Record<string, unknown>).city !== 'string') return false;
  return true;
}

// (functions emitted by Phase 8b appear below this line)
